# terasic_sockit pin map.

Board:
  id: terasic_sockit
  fpga:
    producer: "Altera (Intel)"
    family: "Cyclone V SoC"
    part: 5CSXFC6D6F31C6

  # Quartus project settings:
  # dual-purpose pin reservation, unused-pin state, device I/O default.
  toolchain_options:
    quartus:
      global_assignments:
        - "RESERVE_ALL_UNUSED_PINS_WEAK_PULLUP \"AS INPUT TRI-STATED\""
        - "CYCLONEII_RESERVE_NCEO_AFTER_CONFIGURATION \"USE AS REGULAR IO\""
  pinBanks:
    osc_50_b3b: { pins: AF14, frequency_mhz: 50, iostandard: 1.5 V }   # system clock
    onboard_buttons:
      iostandard: 3.3-V LVTTL
      active: low
      pins: [AE9, AE12, AD9, AD11]
    onboard_leds:
      iostandard: 3.3-V LVTTL
      pins: [AF10, AD10, AE11, AD7]
    clk50mhz: { pins: K14, frequency_mhz: 50, iostandard: 2.5 V }
    cpu_resetn: { pins: AD27, iostandard: 3.3-V LVTTL, active: low }
    onboard_switches:
      iostandard: 2.5 V
      pins: [W25, V25, AC28, AC29]
    onboard_vga:
      iostandard: 3.3-V LVTTL
      pins:
        b: [AE28, Y23, Y24, AG28, AF28, V23, W24, AF29]
        blank_n: AH3
        clk: W20
        g: [Y21, AA25, AB26, AB22, AB23, AA24, AB25, AE27]
        hs: AD12
        r: [AG5, AA12, AB12, AF6, AG6, AJ2, AH5, AJ1]
        sync_n: AG2
        vs: AC12
    onboard_audio_codec:
      iostandard: 3.3-V LVTTL
      pins:
        adc_dat: AC27
        adc_lrck: AG30
        bclk: AE7
        dac_dat: AG3
        dac_lrck: AH4
        i2c_sclk: AH30
        i2c_sdat: AF30
        mute: AD26
        xck: AC9
    onboard_ddr3:
      pins:
        a: [AJ14, AK14, AH12, AJ12, AG15, AH15, AK12, AK13, AH13, AH14, AJ9, AK9, AK7, AK8, AG12]
        ba: [AH10, AJ11, AK11]
        cas_n: AH7
        cke: AJ21
        ck_n: AA15
        ck_p: AA14
        cs_n: AB15
        dm: [AH17, AG23, AK23, AJ27]
        dq: [AF18, AE17, AG16, AF16, AH20, AG21, AJ16, AH18, AK18, AJ17, AG18, AK19, AG20, AF19, AJ20, AH24, AE19, AE18, AG22, AK22, AF21, AF20, AH23, AK24, AF24, AF23, AJ24, AK26, AE23, AE22, AG25, AK27]
        dqs_n: [W16, W17, AA18, AD19]
        dqs_p: [V16, V17, Y17, AC20]
        odt: AE16
        ras_n: AH8
        reset_n: AK21
        rzq: AG17
        we_n: AJ6
      overrides:
        AJ14: SSTL-15 Class I
        AK14: SSTL-15 Class I
        AH12: SSTL-15 Class I
        AJ12: SSTL-15 Class I
        AG15: SSTL-15 Class I
        AH15: SSTL-15 Class I
        AK12: SSTL-15 Class I
        AK13: SSTL-15 Class I
        AH13: SSTL-15 Class I
        AH14: SSTL-15 Class I
        AJ9: SSTL-15 Class I
        AK9: SSTL-15 Class I
        AK7: SSTL-15 Class I
        AK8: SSTL-15 Class I
        AG12: SSTL-15 Class I
        AH10: SSTL-15 Class I
        AJ11: SSTL-15 Class I
        AK11: SSTL-15 Class I
        AH7: SSTL-15 Class I
        AJ21: SSTL-15 Class I
        AA15: Differential 1.5-V SSTL Class I
        AA14: Differential 1.5-V SSTL Class I
        AB15: SSTL-15 Class I
        AH17: SSTL-15 Class I
        AG23: SSTL-15 Class I
        AK23: SSTL-15 Class I
        AJ27: SSTL-15 Class I
        AF18: SSTL-15 Class I
        AE17: SSTL-15 Class I
        AG16: SSTL-15 Class I
        AF16: SSTL-15 Class I
        AH20: SSTL-15 Class I
        AG21: SSTL-15 Class I
        AJ16: SSTL-15 Class I
        AH18: SSTL-15 Class I
        AK18: SSTL-15 Class I
        AJ17: SSTL-15 Class I
        AG18: SSTL-15 Class I
        AK19: SSTL-15 Class I
        AG20: SSTL-15 Class I
        AF19: SSTL-15 Class I
        AJ20: SSTL-15 Class I
        AH24: SSTL-15 Class I
        AE19: SSTL-15 Class I
        AE18: SSTL-15 Class I
        AG22: SSTL-15 Class I
        AK22: SSTL-15 Class I
        AF21: SSTL-15 Class I
        AF20: SSTL-15 Class I
        AH23: SSTL-15 Class I
        AK24: SSTL-15 Class I
        AF24: SSTL-15 Class I
        AF23: SSTL-15 Class I
        AJ24: SSTL-15 Class I
        AK26: SSTL-15 Class I
        AE23: SSTL-15 Class I
        AE22: SSTL-15 Class I
        AG25: SSTL-15 Class I
        AK27: SSTL-15 Class I
        W16: Differential 1.5-V SSTL Class I
        W17: Differential 1.5-V SSTL Class I
        AA18: Differential 1.5-V SSTL Class I
        AD19: Differential 1.5-V SSTL Class I
        V16: Differential 1.5-V SSTL Class I
        V17: Differential 1.5-V SSTL Class I
        Y17: Differential 1.5-V SSTL Class I
        AC20: Differential 1.5-V SSTL Class I
        AE16: SSTL-15 Class I
        AH8: SSTL-15 Class I
        AK21: SSTL-15 Class I
        AG17: SSTL-15
        AJ6: SSTL-15 Class I
    onboard_fan_ctrl: { pins: AG27, iostandard: 3.3-V LVTTL }
    hsmc:
      index_origin: {clkin_n: 1, clkin_p: 1, clkout_n: 1, clkout_p: 1}
      pins:
        clkin_n: [AB27, G15]
        clkin_p: [AA26, H15]
        clkout_n: [E6, A10]
        clkout_p: [E7, A11]
        clk_in0: J14
        clk_out0: AD29
        d: [C10, H13, C9, H12]
        gxb_rx_p: [AE2, AC2, AA2, W2, U2, R2, N2, J2]
        gxb_tx_p: [AD4, AB4, Y4, V4, T4, P4, M4, H4]
        ref_clk_p: P9
        rx_n: [G11, J12, F10, J9, K8, H7, G8, F8, E11, B5, D9, D12, D10, B12, E13, G13, F14]
        rx_p: [G12, K12, G10, J10, K7, J7, H8, F9, F11, B6, E9, E12, D11, C13, F13, H14, F15]
        scl: AA28
        sda: AE29
        tx_n: [A8, D7, F6, C5, C4, E2, D4, B3, D1, C2, B1, A3, A5, B7, B8, B11, A13]
        tx_p: [A9, E8, G7, D6, D5, E3, E4, C3, E1, D2, B2, A4, A6, C7, C8, C12, B13]
      overrides:
        "A10": 2.5 V
        "A11": 2.5 V
        "A13": 2.5 V
        "A3": 2.5 V
        "A4": 2.5 V
        "A5": 2.5 V
        "A6": 2.5 V
        "A8": 2.5 V
        "A9": 2.5 V
        "AA2": 1.5-V PCML
        "AA26": 2.5 V
        "AA28": 2.5 V
        "AB27": 2.5 V
        "AB4": 1.5-V PCML
        "AC2": 1.5-V PCML
        "AD29": 2.5 V
        "AD4": 1.5-V PCML
        "AE2": 1.5-V PCML
        "AE29": 2.5 V
        "B1": 2.5 V
        "B11": 2.5 V
        "B12": 2.5 V
        "B13": 2.5 V
        "B2": 2.5 V
        "B3": 2.5 V
        "B5": 2.5 V
        "B6": 2.5 V
        "B7": 2.5 V
        "B8": 2.5 V
        "C10": 2.5 V
        "C12": 2.5 V
        "C13": 2.5 V
        "C2": 2.5 V
        "C3": 2.5 V
        "C4": 2.5 V
        "C5": 2.5 V
        "C7": 2.5 V
        "C8": 2.5 V
        "C9": 2.5 V
        "D1": 2.5 V
        "D10": 2.5 V
        "D11": 2.5 V
        "D12": 2.5 V
        "D2": 2.5 V
        "D4": 2.5 V
        "D5": 2.5 V
        "D6": 2.5 V
        "D7": 2.5 V
        "D9": 2.5 V
        "E1": 2.5 V
        "E11": 2.5 V
        "E12": 2.5 V
        "E13": 2.5 V
        "E2": 2.5 V
        "E3": 2.5 V
        "E4": 2.5 V
        "E6": 2.5 V
        "E7": 2.5 V
        "E8": 2.5 V
        "E9": 2.5 V
        "F10": 2.5 V
        "F11": 2.5 V
        "F13": 2.5 V
        "F14": 2.5 V
        "F15": 2.5 V
        "F6": 2.5 V
        "F8": 2.5 V
        "F9": 2.5 V
        "G10": 2.5 V
        "G11": 2.5 V
        "G12": 2.5 V
        "G13": 2.5 V
        "G15": 2.5 V
        "G7": 2.5 V
        "G8": 2.5 V
        "H12": 2.5 V
        "H13": 2.5 V
        "H14": 2.5 V
        "H15": 2.5 V
        "H4": 1.5-V PCML
        "H7": 2.5 V
        "H8": 2.5 V
        "J10": 2.5 V
        "J12": 2.5 V
        "J14": 2.5 V
        "J2": 1.5-V PCML
        "J7": 2.5 V
        "J9": 2.5 V
        "K12": 2.5 V
        "K7": 2.5 V
        "K8": 2.5 V
        "M4": 1.5-V PCML
        "N2": 1.5-V PCML
        "P4": 1.5-V PCML
        "P9": HCSL
        "R2": 1.5-V PCML
        "T4": 1.5-V PCML
        "U2": 1.5-V PCML
        "V4": 1.5-V PCML
        "W2": 1.5-V PCML
        "Y4": 1.5-V PCML
    onboard_irda:
      iostandard: 3.3-V LVTTL
      pins:
        rxd: AH2
    onboard_pcie:
      iostandard: 3.3-V LVTTL
      pins:
        perst_n: W22
        wake_n: W21
    onboard_si5338:
      iostandard: 3.3-V LVTTL
      pins:
        scl: AE26
        sda: AJ29
    onboard_temp_sensor:
      iostandard: 3.3-V LVTTL
      pins:
        cs_n: AF8
        din: AG7
        dout: AG1
        sclk: AF9
    onboard_usb:
      iostandard: 1.5 V
      pins:
        clk: AF13
        data: [AK28, AD20, AD21, Y19, AA20, AH27, AF25, AC22]
        empty: AJ4
        full: AK3
        oe_n: AE14
        rd_n: AJ5
        reset_n: AD14
        scl: AK4
        sda: AE13
        wr_n: AK6
