# numato_nereid pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/numato_nereid.py


Board:
  id: numato_nereid
  name: Numato Nereid Kintex-7 PCIe Development Board
  url: https://numato.com/product/nereid-kintex-7-pci-express-fpga-development-board/
  status: active
  producer: numato_lab
  chip: XC7K160T-2FFG676C
  bridges:
  - jtag
  - pcie-jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - usb_jtag_bridge
  - usb_uart_bridge
  - user_leds
  devices:
  - ftdi_ft2232h
  - micron_n25q128a
  - micron_mt41k256m16
  - microsd_socket_generic
  - led_discrete_generic
  banks:
    sys_clk:
      pins: F22
    cpu_resetn:
      pins: C26
    onboard_uart:
      pins:
        tx: H22
        rx: K22
        rts: L22
        cts: L23
        cbus0: K23
    microsd_clk:
      pins:
        pin: G22
    microsd_cmd:
      pins:
        pin: H24
    microsd_dat:
      pins: [F25, E25, J23, H23]
    pcie_clk_n:
      pins:
        pin: K5
    pcie_clk_p:
      pins:
        pin: K6
    pcie_rst_n:
      pins:
        pin: E21
    pcie_rx_n:
      pins: [J3, L3, N3, R3]
    pcie_rx_p:
      pins: [J4, L4, N4, R4]
    pcie_tx_n:
      pins: [H1, K1, M1, P1]
    pcie_tx_p:
      pins: [H2, K2, M2, P2]
    qspi_flash_cs_n:
      pins:
        pin: C23
    qspi_flash_dq:
      pins: [B24, A25, B22, A22]
    qspi_flash_hold:
      pins:
        pin: A22
    qspi_flash_miso:
      pins:
        pin: A25
    qspi_flash_mosi:
      pins:
        pin: B24
    qspi_flash_wp:
      pins:
        pin: B22
    rgb_led_b:
      pins:
        pin: G26
    rgb_led_g:
      pins:
        pin: H26
    rgb_led_r:
      pins:
        pin: J26
