"""
Quartus Prime toolchain driver.

Given a resolved configuration + a user design_top, drive Quartus Prime in batch
mode through analyze/synth/place/route/asm. Artifacts:

    <output>/top.sv             — codegen-produced top module
    <output>/unifpga_top.qsf    — codegen-produced pin + project settings
    <output>/unifpga_top.sdc    — codegen-produced timing constraints
    <output>/unifpga_top.qpf    — minimal Quartus project file
    <output>/quartus.log        — combined Quartus log
    <output>/unifpga_top.sof    — final bitstream (MAX II / MAX V CPLDs emit only unifpga_top.pof)

Set $UNIFPGA_DRY_RUN=1 to generate every artifact without invoking Quartus.
"""

import datetime
import logging
import os
import re
import shutil
import subprocess

from tools import codegen
from tools import source_set


log = logging.getLogger(__name__)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

PROJECT_NAME = "unifpga_top"


def _resolve_quartus_bin(toolchain, name):
    install_dir = os.path.expanduser(toolchain.get("InstallDir") or "").rstrip("/")
    if install_dir:
        candidate = os.path.join(install_dir, "bin", name)
        if os.path.exists(candidate):
            return candidate
    return shutil.which(name)


def _collect_sv_sources(repo, peripherals, user_design_top, generated_top):
    """Quartus compiles every listed file standalone: no .svh; helpers/common ungated."""
    return source_set.collect_sources(
        repo, peripherals, user_design_top, generated_top,
        include_svh=False, gate_helpers=False, gate_common=False)


def _emit_qpf(version):
    """Minimal Quartus Project File. Quartus needs this alongside the .qsf
    even though it's mostly metadata."""
    today = datetime.datetime.now().strftime("%H:%M:%S  %B %d, %Y")
    return (
        "# Auto-generated by uni-fpga.\n"
        'QUARTUS_VERSION = "{}"\n'
        'DATE = "{}"\n\n'
        'PROJECT_REVISION = "{}"\n'.format(version, today, PROJECT_NAME)
    )


def _qsf_file_lines(sv_files, design_top):
    """SYSTEMVERILOG_FILE / VERILOG_FILE assignments to append to the QSF.
    Plus VERILOG_INCLUDE_FILE entries for every `.vh` / `.svh` header found
    under the design directory (recursively). Marking them as include-only
    prevents Quartus's auto-discovery from compiling them standalone, which
    would cause double-declaration errors when the same `.vh` is also pulled
    in via `\\`include`."""
    lines = []
    for sv in sv_files:
        if sv.endswith(".sv"):
            lines.append("set_global_assignment -name SYSTEMVERILOG_FILE {}".format(sv))
        elif sv.endswith(".v"):
            lines.append("set_global_assignment -name VERILOG_FILE {}".format(sv))

    design_dir = os.path.dirname(os.path.abspath(design_top))
    if os.path.isdir(design_dir):
        for root, _dirs, names in os.walk(design_dir):
            for name in sorted(names):
                if name.endswith(".vh") or name.endswith(".svh"):
                    full = os.path.join(root, name)
                    lines.append("set_global_assignment -name VERILOG_INCLUDE_FILE {}".format(full))
    return lines


def _qsf_search_path_lines(design_top, output_dir):
    """SEARCH_PATH entries for `\\`include` and `$readmemh()` resolution.
    Only the design dir, output dir, and shared peripherals dirs — NOT
    subdirectories. Auto-discovery in Quartus rescans every file in
    SEARCH_PATH for module declarations, which causes duplicate-declaration
    errors when sibling .vh files are also included via `\\`include` from a
    parent source file. Quartus already resolves `\\`include "name.vh"` relative
    to the including file's directory, so cpu/ subdirs don't need explicit
    paths."""
    design_dir = os.path.dirname(os.path.abspath(design_top))
    paths = [design_dir, os.path.abspath(output_dir),
             os.path.join(REPO, "rtl", "peripherals"),
             os.path.join(REPO, "rtl", "peripherals", "designs_common")]
    seen = set()
    out = []
    for p in paths:
        if os.path.isdir(p) and p not in seen:
            seen.add(p)
            out.append('set_global_assignment -name SEARCH_PATH "{}"'.format(p))
    return out


def _select_part(board, configuration):
    """Pick the part name. Honours configuration.part for boards with multiple
    Parts (analogous to Vivado driver). Normalizes for Quartus's device list:
    Cyclone V parts often carry a trailing `N` (manufacturing/temp marker) in
    datasheet names, but Quartus's device.db only accepts the base form."""
    part_name = board.get("Part") or ""
    if not part_name and isinstance(board.get("Parts"), list):
        wanted = (configuration.get("part") or "").lower()
        chosen = None
        for entry in board["Parts"]:
            if wanted and entry.get("Name", "").lower() == wanted:
                chosen = entry
                break
        if chosen is None:
            chosen = board["Parts"][0]
            log.info("Board %s has multiple Parts; defaulting to %s",
                     board["Id"], chosen.get("Name") or chosen.get("Part"))
        part_name = chosen.get("Part") or ""

    # Strip trailing N (Cyclone V "no temp/lead" marker — not in Quartus device list).
    if part_name.endswith("N") and (part_name.startswith("5C") or part_name.startswith("EP")):
        part_name = part_name[:-1]
    return part_name


def synthesize(*, dir, configuration, board, board_pinmap, toolchain, peripherals,
               top, generated_top=None, include=None, output, step="full", **_):
    """Synthesize through Quartus. Returns 0 on success."""
    resolved = {
        "configuration": configuration,
        "board":         board,
        "board_pinmap":  board_pinmap,
        "toolchain":     toolchain,
        "peripherals":   peripherals,
    }

    if generated_top is None:
        generated_top = os.path.join(output, "top.sv")
        with open(generated_top, "w") as f:
            f.write(codegen.emit_top_sv(resolved, design=top))

    part_name = _select_part(board, configuration)
    if not part_name:
        log.error("Board %s has no 'Part' field — cannot drive Quartus.", board["Id"])
        return 1

    sv_files = _collect_sv_sources(REPO, peripherals, top, generated_top)

    qsf_path = os.path.join(output, PROJECT_NAME + ".qsf")
    sdc_path = os.path.join(output, PROJECT_NAME + ".sdc")
    qpf_path = os.path.join(output, PROJECT_NAME + ".qpf")

    qsf_text = codegen.emit_qsf(resolved, part_name)
    qsf_text += "\n# ---- Search paths (for `include / $readmemh) ----\n"
    qsf_text += "\n".join(_qsf_search_path_lines(top, output)) + "\n"
    qsf_text += "\n# ---- Source files ----\n"
    qsf_text += "\n".join(_qsf_file_lines(sv_files, top)) + "\n"
    qsf_text += "set_global_assignment -name SDC_FILE {}\n".format(PROJECT_NAME + ".sdc")
    with open(qsf_path, "w") as f:
        f.write(qsf_text)
    log.info("Wrote %s", qsf_path)

    with open(sdc_path, "w") as f:
        f.write(codegen.emit_sdc(resolved))
    log.info("Wrote %s", sdc_path)

    with open(qpf_path, "w") as f:
        f.write(_emit_qpf(toolchain.get("Version") or "23.1std"))

    log.info("Source files (%d):", len(sv_files))
    for sv in sv_files:
        log.info("  - %s", os.path.relpath(sv, REPO) if sv.startswith(REPO) else sv)

    if os.environ.get("UNIFPGA_DRY_RUN"):
        log.info("[dry run] Quartus not invoked. Artifacts in %s", output)
        return 0

    quartus_sh = _resolve_quartus_bin(toolchain, "quartus_sh")
    quartus_map = _resolve_quartus_bin(toolchain, "quartus_map")
    if quartus_sh is None or quartus_map is None:
        log.error("Could not locate quartus_sh / quartus_map. Set toolchain.InstallDir "
                  "in config/toolchains.yml or put quartus_sh on $PATH.")
        return 1

    if step == "elaborate":
        # Analysis & elaboration only — fast equivalent of Vivado synth_design -rtl.
        cmd = [quartus_map, "--analysis_and_elaboration", PROJECT_NAME]
    else:
        # `full` and `pnr` both run the standard map → fit → asm → sta flow.
        cmd = [quartus_sh, "--flow", "compile", PROJECT_NAME]

    log.info("Invoking Quartus: %s", " ".join(cmd))
    log_path = os.path.join(output, "quartus.log")
    # Force the 64-bit binary on Quartus II 13.x (the bin/ wrapper defaults to
    # the 32-bit one, which is markedly slower on big designs). Modern Quartus
    # Prime (20.1+) is 64-bit-only and ignores this env var. The 64-bit Q13
    # binary needs linux64/ on LD_LIBRARY_PATH for libaxerces-c.so.26 etc.;
    # the wrapper only sets it for a subset of subcommands, so do it here too.
    env = dict(os.environ)
    env["QUARTUS_64BIT"] = "1"
    install_dir = os.path.expanduser(toolchain.get("InstallDir") or "").rstrip("/")
    lib64 = os.path.join(install_dir, "linux64")
    if os.path.isdir(lib64):
        env["LD_LIBRARY_PATH"] = lib64 + ":" + env.get("LD_LIBRARY_PATH", "")
    _preload_allocator(env, toolchain)
    with open(log_path, "w") as logf:
        try:
            rc = subprocess.run(cmd, cwd=output, env=env,
                                stdout=logf, stderr=subprocess.STDOUT).returncode
        except FileNotFoundError as exc:
            log.error("Quartus invocation failed: %s", exc)
            return 1

    if rc != 0:
        log.error("Quartus exited with code %d (see %s)", rc, log_path)
        return rc

    bitstream = _find_bitstream(output)
    if bitstream:
        log.info("Bitstream ready: %s", bitstream)
    return 0


# Quartus II 13.x on Linux replaces malloc with its bundled TBB allocator
# (linux64/libtbbmalloc_proxy.so.2). On a large part (EP3C120) quartus_fit
# deadlocks in it: BackRefIdx::newBackRef mallocs, re-enters newBackRef and
# spins in sched_yield on the lock it already holds (route-lookahead matrix
# allocation), so the fitter sits at 100 % CPU with no output. A standalone
# allocator preloaded ahead of the proxy takes malloc over and the fit
# finishes (dk_dev_3c120n: 15 s).
_ALLOCATORS = ("libjemalloc.so.2", "libtcmalloc_minimal.so.4", "libmimalloc.so.2")
_LIB_DIRS = ("/usr/lib/x86_64-linux-gnu", "/usr/lib64", "/usr/lib", "/usr/local/lib")


def _preload_allocator(env, toolchain, lib_dirs=_LIB_DIRS, system=None):
    """Put a standalone malloc on LD_PRELOAD for Quartus II 13.x on Linux.
    $UNIFPGA_QUARTUS_MALLOC names the library to use, or `off` to skip.
    Returns the library preloaded, or None."""
    if (system or os.uname().sysname) != "Linux" or not str(toolchain.get("Version") or "").startswith("13"):
        return None
    choice = env.get("UNIFPGA_QUARTUS_MALLOC")
    if choice == "off":
        return None
    candidates = [choice] if choice else [os.path.join(d, name) for name in _ALLOCATORS for d in lib_dirs]
    lib = next((c for c in candidates if os.path.isfile(c)), None)
    if lib is None:
        log.warning("Quartus II 13.x: no standalone malloc found (%s); quartus_fit can hang on large "
                    "parts inside its bundled TBB allocator. Install jemalloc or set "
                    "UNIFPGA_QUARTUS_MALLOC to a malloc library.", ", ".join(_ALLOCATORS))
        return None
    env["LD_PRELOAD"] = lib + (" " + env["LD_PRELOAD"] if env.get("LD_PRELOAD") else "")
    log.info("Quartus II 13.x: preloading %s instead of the bundled TBB malloc", lib)
    return lib


def _find_bitstream(output):
    """The programming file Quartus produced: unifpga_top.sof (SRAM object
    file, FPGAs) or unifpga_top.pof — MAX II / MAX V CPLD builds (quartus2,
    e.g. omdazz_epm570) emit only the flash programmer object file. Prefers
    .sof; None when neither exists."""
    for ext in (".sof", ".pof"):
        path = os.path.join(output, PROJECT_NAME + ext)
        if os.path.exists(path):
            return path
    return None


def _cables(quartus_pgm, env, cwd):
    """Cable names from `quartus_pgm -l` ("1) USB-Blaster [1-2]")."""
    try:
        out = subprocess.run([quartus_pgm, "-l"], cwd=cwd, env=env, stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, universal_newlines=True).stdout
    except OSError as exc:
        log.error("quartus_pgm -l failed: %s", exc)
        return []
    return [m.group(1).strip() for m in re.finditer(r"^\s*\d+\)\s+(.+?)\s*$", out, re.M)]


def program(*, board, board_pinmap=None, toolchain, output, **_):
    """Download the bitstream over JTAG with quartus_pgm: the first cable
    `quartus_pgm -l` lists (warn on more), `.sof` else `.pof` (MAX II), the
    FPGA's index in the JTAG chain from the pinmap
    (`toolchain_options.quartus.jtag_device_index`: 2 behind the HPS on the
    DE1-SoC / DE10-Nano)."""
    bitstream = _find_bitstream(output)
    dry = bool(os.environ.get("UNIFPGA_DRY_RUN"))
    if bitstream is None and not dry:
        log.error("Bitstream not found: %s.sof / .pof in %s — run synthesis first", PROJECT_NAME, output)
        return 1
    if bitstream is None:
        bitstream = os.path.join(output, PROJECT_NAME + ".sof")
    opts = ((board_pinmap or {}).get("toolchain_options") or {}).get("quartus") or {}
    index = opts.get("jtag_device_index")
    target = "P;{}{}".format(bitstream, "@{}".format(index) if index else "")
    if dry:
        log.info("[dry run] Would program %s", target)
        return 0
    quartus_pgm = _resolve_quartus_bin(toolchain, "quartus_pgm")
    if quartus_pgm is None:
        log.error("Could not locate quartus_pgm.")
        return 1
    env = dict(os.environ)
    env["QUARTUS_64BIT"] = "1"
    cables = _cables(quartus_pgm, env, output)
    if not cables:
        log.error("quartus_pgm lists no cable. Is the USB-Blaster connected? On Linux the udev rules for it "
                  "(an Intel FPGA .rules file in /etc/udev/rules.d) must be installed; "
                  "a stale jtagd can be stopped with `killall jtagd`.")
        return 1
    if len(cables) > 1:
        log.warning("more than one cable is connected: %s; using %s", ", ".join(cables), cables[0])
    cmd = [quartus_pgm, "--no_banner", "-c", cables[0], "--mode=jtag", "-o", target]
    log.info("Programming via: %s", " ".join(cmd))
    rc = subprocess.run(cmd, cwd=output, env=env).returncode
    if rc != 0:
        log.error("Programming failed (exit %d). Is the board powered and the cable driver installed?", rc)
    return rc
