# Achronix / Speedster 22i — chip registry
# Intel 22 nm Achronix FPGA. ACE.

Family:
  id: speedster_22i
  producer: achronix
  name: Speedster 22i
  description: Intel 22 nm Achronix FPGA. ACE.
  default_toolchains:
    - ace[*]
  chips:
    - id: AC22iHD1000
