# Pangomicro / Logos — chip registry

Family:
  id: logos
  producer: pangomicro
  name: Logos
  description: ""
  default_toolchains:
    - pango_ds[*]
  chips:
    - id: PGL12G-6MBG324
    - id: PGL22G-MBG324
    - id: PGL22G-6MBG324
    - id: PGL22G-6CMBG324
    - id: PGL25G2-6CMBG324
    - id: PGL50G-6IFBG484
    - id: PGL50H-6IFBG484
    - id: PGL12G-6CFBG256
