# alinx_ax516: AX516.

Board:
  id: alinx_ax516
  name: AX516
  url: https://alinx.com/en/detail/35
  producer: alinx
  chip: XC6SLX16-2CSG324
  bridges:
  - jtag
  programmer: ise_impact
  features:
  - microsd_socket
  - sdr_sdram
  - seven_segment_display
  - usb_uart_bridge
  - user_buttons
  - user_leds
  - vga_output
  devices:
  - winbond_w9825g6kh
  - silabs_cp2102
  - vga666_resistor_dac
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
  - seven_seg_module_shared
