# Efinix / Trion
# 40 nm Quantum-architecture FPGA. Efinity.

Producer: Efinix
Family: Trion
Description: 40 nm Quantum-architecture FPGA. Efinity.
Boards:
  - Id: efinix_t120_bga324_devkit
    BoardName: Trion T120 BGA324 Development Kit
    Devices:
      - ftdi_ft2232h
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
    BoardProducer: efinix
    Chip: T120F324C4
    Bridges:
      - usb-jtag
    Programmer: efinity_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - dip_switches
      - ethernet_phy_10_100
      - ethernet_phy_gigabit
      - hdmi_output
      - jtag_header
      - microsd_socket
      - mipi_csi2_input
      - pmod_connector
      - raspi_hat_header
      - usb_jtag_bridge
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://www.efinixinc.com/products-devkits-triont120bga324.html
    Status: active
  - Id: efinix_t120_bga576_devkit
    BoardName: Trion T120 BGA576 Development Kit
    Features:
      - usb_jtag_bridge
      - user_buttons
      - user_leds
    Devices:
      - ftdi_ft2232h
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: efinix
    Chip: T120F576C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: "https://www.efinixinc.com/products-devkits-triont120bga576.html"
  - Id: efinix_t13_bga169_devkit
    BoardName: Trion T13 BGA169 Development Kit
    BoardProducer: efinix
    Chip: T13F169C3
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Status: eol
  - Id: efinix_t20_bga169_devkit
    BoardName: Trion T20 BGA169 Development Kit
    Features:
      - usb_jtag_bridge
      - user_buttons
      - user_leds
    Devices:
      - ftdi_ft2232h
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: efinix
    Chip: T20F169C3
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: https://www.efinixinc.com/products-devkits-triont20.html
  - Id: efinix_t20_mipi_devkit
    BoardName: Trion T20 MIPI Development Kit
    Devices:
      - ftdi_ft2232h
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: efinix
    Chip: T20F169C3
    Bridges:
      - usb-jtag
    Programmer: efinity_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - mipi_csi2_input
      - user_leds
      - user_buttons
      - usb_uart_bridge
      - usb_jtag_bridge
      - usb_powered
    BoardURL: https://www.efinixinc.com/products-devkits-triont20-mipi.html
    Status: active
  - Id: efinix_t35_bga324_devkit
    BoardName: Trion T35 BGA324 Development Kit
    BoardProducer: efinix
    Chip: T35F324C3
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Status: eol
  - Id: efinix_t8_bga81_devkit
    BoardName: Trion T8 BGA81 Development Kit
    Devices:
      - ftdi_ft2232h
    BoardProducer: efinix
    Chip: T8F81C2
    Bridges:
      - usb-jtag
    Programmer: efinity_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - user_leds
      - user_buttons
      - usb_uart_bridge
      - usb_jtag_bridge
      - usb_powered
    BoardURL: https://www.efinixinc.com/products-devkits-triont8.html
    Status: active
  - Id: efinix_xyloni
    BoardName: Xyloni Dev Kit
    Features:
      - microsd_socket
    Devices:
      - microsd_socket_generic
    BoardProducer: efinix
    Chip: T8F81C2
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: https://www.efinixinc.com/products-devkits-xyloni.html
  - Id: fireant
    BoardName: FireAnt
    Features:
      - usb_jtag_bridge
      - user_buttons
      - user_leds
    Devices:
      - ftdi_ft232h
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: efinix
    Chip: T8F81
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Status: eol
  - Id: trion_t20
    BoardName: Trion T20
    BoardURL: "https://www.efinixinc.com/products-devkits-triont20.html"
    BoardProducer: efinix
    Chip: T20F256C2
    Bridges:
      - jtag
    Programmer: efinity_pgm
  - Id: vicharak_vaaman
    BoardName: Vicharak Vaaman
    BoardProducer: vicharak
    Chip: T120F324C
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Features:
      - ddr3_memory
      - lpddr4_memory
      - emmc_flash
      - microsd_socket
      - hdmi_output
      - mipi_csi2_input
      - mipi_dsi_output
      - ethernet_phy_gigabit
      - usb_2_otg
      - usb_3_host
      - wifi_radio
      - bluetooth_le_radio
      - audio_codec
      - pcie_endpoint
      - jtag_header
    BoardURL: https://vicharak.in/vaaman
    Status: active
