# myir_zturn_7010: MYIR Z-turn Board (XC7Z010).

Board:
  id: myir_zturn_7010
  name: MYIR Z-turn Board (XC7Z010)
  url: https://www.myirtech.com/list.asp?id=502
  status: active
  producer: myir
  chip: XC7Z010-1CLG400C
  bridges:
  - jtag
  programmer: vivado_hw
  extra_programmers:
  - openFPGALoader[*]
  features:
  - ddr3_memory
  - qspi_flash
  - microsd_socket
  - ethernet_phy_gigabit
  - usb_2_otg
  - usb_uart_bridge
  - hdmi_output
  - can_transceiver
  - user_buttons
  - user_leds
  - jtag_header
  devices:
  - silabs_cp2102
  - micron_mt41k128m16
  - macronix_mx25l25645g
  - realtek_rtl8211e
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
