# trenz_te0700: TE0700.

Board:
  id: trenz_te0700
  name: TE0700
  url: https://shop.trenz-electronic.de/en/Products/Trenz-Electronic/TE07XX-Zynq-SoC/
  producer: trenz_electronic
  chip: XC7Z020-1CLG484C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - qspi_flash
  devices:
  - micron_mt41k128m16
  - micron_n25q128a
