# Altera (Intel) / Agilex 3
# Newest low-cost Agilex (2024). Quartus Prime Pro.

Producer: Altera (Intel)
Family: Agilex 3
Description: Newest low-cost Agilex (2024). Quartus Prime Pro.
Boards:
  - Id: intel_agilex3_devkit
    BoardName: Agilex 3 FPGA Development Kit
    Features:
      - ddr4_memory
      - dip_switches
      - ethernet_phy_gigabit
      - microsd_socket
      - qspi_flash
      - usb_jtag_bridge
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Devices:
      - micron_mt40a256m16
      - micron_n25q256a
      - microchip_ksz9031rnx
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
    BoardProducer: intel_altera
    Chip: A3CW135BM16AE6S
    Bridges:
      - jtag
    Programmer: quartus_pgm
    BoardURL: "https://www.altera.com/products/devkit/po-3000/agilex-3-fpga-and-soc-c-series-development-kit"
  - Id: terasic_de23_lite
    BoardName: DE23-Lite Development Kit
    Devices:
      - winbond_w9825g6kh
      - usb_blaster_ii_built_in
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - seven_seg_module_shared
      - ti_adc128s022
    BoardProducer: terasic
    Chip: A3CZ135BB18AE7S
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - adc_chip
      - dip_switches
      - hdmi_output
      - sdr_sdram
      - seven_segment_display
      - usb_jtag_bridge
      - user_buttons
      - user_leds
    BoardURL: https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=1383
    Status: active
