# Altera (Intel) / Cyclone 10
# Refresh of Cyclone family. Cyclone 10 LP = Lite; Cyclone 10 GX = Prime Pro.

Producer: Altera (Intel)
Family: Cyclone 10
Description: Refresh of Cyclone family. Cyclone 10 LP = Lite; Cyclone 10 GX = Prime Pro.
Boards:
  - Id: intel_cyclone10gx_devkit
    BoardName: Cyclone 10 GX FPGA Development Kit
    Features:
      - ddr4_memory
      - dip_switches
      - ethernet_phy_gigabit
      - microsd_socket
      - qspi_flash
      - usb_jtag_bridge
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Devices:
      - micron_mt40a256m16
      - micron_n25q256a
      - microchip_ksz9031rnx
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
    BoardProducer: intel_altera
    Chip: 10CX220YF780E5G
    Bridges:
      - jtag
    Programmer: quartus_pgm
    Status: eol
  - Id: intel_cyclone10lp_evalkit
    BoardName: Cyclone 10 LP Evaluation Kit
    Features:
      - ddr3_memory
      - dip_switches
      - ethernet_phy_10_100
      - usb_jtag_bridge
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Devices:
      - micron_mt41k256m16
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - microchip_lan8742a
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
    BoardProducer: intel_altera
    Chip: 10CL025YU256I7G
    Bridges:
      - jtag
    Programmer: quartus_pgm
    Status: eol
  - Id: intel_cyclone10lp_starter
    BoardName: Cyclone 10 LP FPGA Starter Kit
    Devices:
      - micron_mt41k256m16
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - seven_seg_module_shared
    BoardProducer: intel_altera
    Chip: 10CL025YU256C8G
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - arduino_shield_header
      - ddr3_memory
      - dip_switches
      - seven_segment_display
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Status: eol
  - Id: qmtech_cyc10lp_10cl025_core
    BoardName: QMtech Cyclone 10 LP 10CL025 Core Board
    Aliases: [qmtech_cyc10lp_core]
    Devices:
      - winbond_w9825g6kh
      - winbond_w25q128
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: qmtech
    Chip: 10CL025YU256C8G
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - qspi_flash
      - sdr_sdram
      - spi_flash
      - user_buttons
      - user_leds
    BoardURL: https://qmtech.aliexpress.com/store/1199788
    Status: active
  - Id: qmtech_cyc10lp_10cl055_core
    BoardName: QMtech Cyclone 10 LP 10CL055 Core Board
    Devices:
      - winbond_w9825g6kh
      - winbond_w25q128
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: qmtech
    Chip: 10CL055YU484C8G
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - qspi_flash
      - sdr_sdram
      - spi_flash
      - user_buttons
      - user_leds
    BoardURL: https://qmtech.aliexpress.com/store/1199788
    Status: active
  - Id: qmtech_cyc10lp_10cl080_core
    BoardName: QMtech Cyclone 10 LP 10CL080 Core Board
    Devices:
      - winbond_w9825g6kh
      - winbond_w25q128
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: qmtech
    Chip: 10CL080YU484C8G
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - qspi_flash
      - sdr_sdram
      - spi_flash
      - user_buttons
      - user_leds
    BoardURL: https://qmtech.aliexpress.com/store/1199788
    Status: active
  - Id: qmtech_cyc10lp_10cl120_core
    BoardName: QMtech Cyclone 10 LP 10CL120 Core Board
    Devices:
      - winbond_w9825g6kh
      - winbond_w25q128
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: qmtech
    Chip: 10CL120YF484C8G
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - qspi_flash
      - sdr_sdram
      - spi_flash
      - user_buttons
      - user_leds
    BoardURL: https://qmtech.aliexpress.com/store/1199788
    Status: active
  - Id: alinx_ax1006
    BoardName: "Alinx AX1006"
    Devices:
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - vga666_resistor_dac
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - seven_seg_module_shared
      - winbond_w9825g6kh
    BoardProducer: alinx
    Chip: 10CL006YU256C8G
    Bridges:
      - jtag
    Programmer: quartus_pgm
    Features:
      - jtag_header
      - microsd_socket
      - sdr_sdram
      - seven_segment_display
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
      - vga_output
    BoardURL: https://www.en.alinx.com
    Status: active
  - Id: alinx_ax1016
    BoardName: "Alinx AX1016"
    Devices:
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - vga666_resistor_dac
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - seven_seg_module_shared
      - winbond_w9825g6kh
    BoardProducer: alinx
    Chip: 10CL016YU256C8G
    Bridges:
      - jtag
    Programmer: quartus_pgm
    Features:
      - jtag_header
      - microsd_socket
      - sdr_sdram
      - seven_segment_display
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
      - vga_output
    BoardURL: https://www.en.alinx.com
    Status: active
  - Id: alinx_ax1025
    BoardName: "Alinx AX1025"
    Devices:
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - vga666_resistor_dac
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - seven_seg_module_shared
      - winbond_w9825g6kh
    BoardProducer: alinx
    Chip: 10CL025YU256C8G
    Bridges:
      - jtag
    Programmer: quartus_pgm
    Features:
      - jtag_header
      - microsd_socket
      - sdr_sdram
      - seven_segment_display
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
      - vga_output
    BoardURL: https://www.en.alinx.com
    Status: active
