# Altera (Intel) / MAX II CPLD
# Smaller flash CPLD. Quartus II.

Producer: Altera (Intel)
Family: MAX II CPLD
Description: Smaller flash CPLD. Quartus II.
Boards:
  - Id: intel_maxv_cpld_evalkit
    BoardName: MAX V CPLD Development Kit
    Devices:
      - usb_blaster_ii_built_in
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - seven_seg_module_shared
    BoardProducer: intel_altera
    Chip: 5M570ZF256C5N
    Bridges:
      - usb-jtag
    Programmer: quartus_pgm
    Features:
      - dip_switches
      - seven_segment_display
      - usb_jtag_bridge
      - usb_powered
      - user_buttons
      - user_leds
    Status: eol
  - Id: omdazz_epm570
    BoardName: Omdazz EPM570
    BoardProducer: omdazz
    Chip: EPM570T100C5
    Bridges:
      - jtag
    Programmer: quartus2_pgm
