# alinx_z19_p pin map.
# Source type: github_xdc
#   https://github.com/alinxalinx/Z19_P/blob/master/vivado/auto_create_project/src/constraints/system.xdc


Board:
  id: alinx_z19_p
  name: Alinx Z19-P
  url: https://coderobin.com/products/alinx-z19-p-xilinx-zynq-ultrascale-mpsoc-xczu19eg-fpga-development-board
  status: active
  notes: Premium ZU19EG variant — PCIe Gen3 x16 + 16x GTY 32.75 Gb/s.
  producer: alinx
  chip: XCZU19EG-2FFVC1760I
  bridges:
  - usb-jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - displayport_output
  - emmc_flash
  - ethernet_phy_gigabit
  - fmc_hpc
  - microsd_socket
  - pcie_endpoint
  - qsfp_cage
  - qsfp_dd_cage
  - qspi_flash
  - sd_card_socket
  - usb_3_host
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - silabs_cp2102
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
  banks:
    sys_clk_diff:
      pins:
        p: H21
      frequency_mhz: 200
    onboard_leds:
      pins:
      - E10
      - E11
    onboard_uart:
      pins:
        tx: M12
        rx: M11
    fan_pwm:
      pins: F4
