# efinix_topaz_tz170_j484_devkit pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/efinix_tz170_j484_dev_kit.py


Board:
  id: efinix_topaz_tz170_j484_devkit
  name: Topaz Tz170 J484 Development Kit
  url: https://www.efinixinc.com/products-devkits-topaztz170j484.html
  status: active
  producer: efinix
  chip: Tz170J484C4
  bridges:
  - jtag
  - usb_uart
  programmer: efinity_pgm
  features:
  - jtag_header
  - usb_uart_bridge
  - mipi_dsi_output
  - mipi_csi2_input
  - lpddr4_memory
  - microsd_socket
  - user_leds
  - user_buttons
  - spi_flash
  - fmc_lpc
  devices:
  - microsd_socket_generic
  banks:
    sys_clk:
      pins: C1
    onboard_leds:
      pins: [E1, F1, C2, E3, B1, B2]
    onboard_uart:
      pins:
        tx: G10
        rx: F8
    microsd_clk:
      pins:
        pin: F16
    microsd_cmd:
      pins:
        pin: F17
    microsd_data:
      pins: [G15, F15, H15, G17]
    qspi_flash_clk:
      pins:
        pin: J2
    qspi_flash_cs_n:
      pins:
        pin: A2
    qspi_flash_dq:
      pins: [F5, E5, B5, C5]
    qspi_flash_miso:
      pins:
        pin: E5
    qspi_flash_mosi:
      pins:
        pin: F5
