# dk_dev_3c120n pin map.

Board:
  id: dk_dev_3c120n
  fpga:
    producer: "Altera (Intel)"
    family: "Cyclone III"
    part: EP3C120F780C6
  defaults:
    iostandard: 2.5 V

  # Quartus project settings:
  # dual-purpose pin reservation, unused-pin state, device I/O default.
  toolchain_options:
    quartus:
      global_assignments:
        - "NOMINAL_CORE_SUPPLY_VOLTAGE 1.2V"
        - "CYCLONEIII_CONFIGURATION_SCHEME \"PASSIVE SERIAL\""
        - "ON_CHIP_BITSTREAM_DECOMPRESSION OFF"
        - "USE_CONFIGURATION_DEVICE OFF"
        - "FORCE_CONFIGURATION_VCCIO ON"
        - "STRATIX_DEVICE_IO_STANDARD \"2.5 V\""
        - "RESERVE_DATA0_AFTER_CONFIGURATION \"USE AS REGULAR IO\""
        - "CYCLONEII_RESERVE_NCEO_AFTER_CONFIGURATION \"USE AS REGULAR IO\""
        - "RESERVE_DATA0_AFTER_CONFIGURATION \"AS INPUT TRI-STATED\""
  pinBanks:
    clk50mhz: { pins: AH15, frequency_mhz: 50, iostandard: 1.8 V }
    clk125mhz: { pins: A14, frequency_mhz: 125, iostandard: 1.8 V }
    clkin_sma: { pins: AH14, iostandard: 1.8 V }
    clkout_sma: { pins: AE23, iostandard: 1.8 V }
    altera_config_dclk: { pins: P3 }
    altera_config_data0: { pins: N7 }
    termination_blk0:
      pins:
        rup: AA17
        rdn: AB17
    termination_blk1:
      pins:
        rup: F19
        rdn: E19
    termination_blk2:
      pins:
        rup: U7
        rdn: U8
    termination_blk3:
      pins:
        rup: AA22
        rdn: AB23
    onboard_ddr2_top:
      pins:
        wen: A10
        rasn: F8
        casn: F14
        cke: E21
        csn: C7
        odt: A6
        a: [J13, G18, E8, D24, D7, J15, H15, J16, H8, D16, A17, D8, D25, F15, B12, H16]
        ba: [C23, D19, C26]
        active: E10
      overrides:
        "A10": SSTL-18 CLASS I
        "A17": SSTL-18 CLASS I
        "A6": SSTL-18 CLASS I
        "B12": SSTL-18 CLASS I
        "C23": SSTL-18 CLASS I
        "C26": SSTL-18 CLASS I
        "C7": SSTL-18 CLASS I
        "D16": SSTL-18 CLASS I
        "D19": SSTL-18 CLASS I
        "D24": SSTL-18 CLASS I
        "D25": SSTL-18 CLASS I
        "D7": SSTL-18 CLASS I
        "D8": SSTL-18 CLASS I
        "E10": 1.8 V
        "E21": SSTL-18 CLASS I
        "E8": SSTL-18 CLASS I
        "F14": SSTL-18 CLASS I
        "F15": SSTL-18 CLASS I
        "F8": SSTL-18 CLASS I
        "G18": SSTL-18 CLASS I
        "H15": SSTL-18 CLASS I
        "H16": SSTL-18 CLASS I
        "H8": SSTL-18 CLASS I
        "J13": SSTL-18 CLASS I
        "J15": SSTL-18 CLASS I
        "J16": SSTL-18 CLASS I
    onboard_ddr2_bot:
      pins:
        wen: AE5
        rasn: AE21
        casn: AD21
        cke: AG4
        csn: AC21
        odt: AE24
        a: [AB22, AG6, Y13, AE7, AB12, AC7, AD12, AB8, AH12, AB10, AE4, AF21, Y12, Y14, AF12, AA16]
        ba: [AF3, AF5, AH4]
        active: AA14
      overrides:
        "AA14": 1.8 V
        "AA16": SSTL-18 CLASS I
        "AB10": SSTL-18 CLASS I
        "AB12": SSTL-18 CLASS I
        "AB22": SSTL-18 CLASS I
        "AB8": SSTL-18 CLASS I
        "AC21": SSTL-18 CLASS I
        "AC7": SSTL-18 CLASS I
        "AD12": SSTL-18 CLASS I
        "AD21": SSTL-18 CLASS I
        "AE21": SSTL-18 CLASS I
        "AE24": SSTL-18 CLASS I
        "AE4": SSTL-18 CLASS I
        "AE5": SSTL-18 CLASS I
        "AE7": SSTL-18 CLASS I
        "AF12": SSTL-18 CLASS I
        "AF21": SSTL-18 CLASS I
        "AF3": SSTL-18 CLASS I
        "AF5": SSTL-18 CLASS I
        "AG4": SSTL-18 CLASS I
        "AG6": SSTL-18 CLASS I
        "AH12": SSTL-18 CLASS I
        "AH4": SSTL-18 CLASS I
        "Y12": SSTL-18 CLASS I
        "Y13": SSTL-18 CLASS I
        "Y14": SSTL-18 CLASS I
    onboard_ddr2:
      iostandard: SSTL-18 CLASS I
      pins:
        dq: [AG22, AH21, AH22, AG21, AD17, AH23, AE19, AF24, AG18, AG17, AH18, AH17, AF15, AE17, AF16, AB16, AE11, AG11, AG10, AH11, AE9, AE12, AF10, AE13, AC8, AH7, AG8, AH8, AG7, AA10, AF7, AD10, A12, C14, A11, C13, D15, C12, E14, D13, B7, C11, A7, C10, E11, B6, H13, D10, C17, B19, B18, C19, D20, C16, A19, E17, C21, C22, A21, A22, C24, B21, D21, E18, E22, C25, A23, B25, A26, F21, B26, D22]
        dqs: [AE18, AF17, AF11, AE10, D12, E12, B17, D17, A25]
        dm: [AH19, AC15, AF8, AB9, B10, A8, E15, C20, B23]
        ck_p: [AE14, H12, J19]
        ck_n: [AF14, G11, H19]
    onboard_analog:
      pins:
        scl: R1
        sda: M1
    pclk_0:
      iostandard: SSTL-2 CLASS II
      pins:
        p: G6
        n: G5
    pclk_1:
      iostandard: SSTL-2 CLASS II
      pins:
        p: D2
        n: D1
    onboard_adc_a:
      pins:
        d: [P1, P2, M7, M8, R4, R3, T3, T4, V3, V4, R6, R7, AE3, AB6]
        oe: M3
        dco: J2
        or: M4
        cs: M2
    onboard_adc_b:
      pins:
        d: [U1, U2, V1, V2, W1, W2, U4, U3, Y3, Y4, AB1, AB2, AF5, AF2]
        oe: U5
        dco: J1
        or: U6
        cs: R2
      overrides:
        "AF5": SSTL-18 CLASS I
    onboard_dac_a:
      pins:
        d: [F4, F5, G1, G2, K7, J7, J3, J4, K3, K4, L8, K8, L6, L7]
    onboard_dac_b:
      pins:
        d: [G3, G4, H3, H4, J5, J6, K1, K2, L1, L2, L3, L4, N3, N4]
    onboard_ethernet_phy:
      pins:
        mdc: N8
        mdio: L5
        rx_clk: B14
        tx_en: AA7
        gtx_clk: T8
        rxd: [W8, AA6, W7, Y6]
        txd: [W4, AA5, Y5, W3]
        rx_dv: AB4
        resetn: AD2
        led_link1000: AC25
      overrides:
        "B14": 1.8 V
    onboard_parallel_flash:
      iostandard: 1.8 V
      pins:
        oen: Y17
        wen: AA21
        cen: Y16
        rdybsyn: AG25
        resetn: AB20
    onboard_sram:
      iostandard: 1.8 V
      pins:
        ben: [AF20, AH26, AE22, AB21]
        clk: AD22
        csn: AB19
        oen: AD25
        wen: AE25
        wait: [AG15, AH25]
        psn: B4
        advn: AA19
    onboard_flash_sram:
      iostandard: 1.8 V
      pins:
        a: [AC11, AH10, AA13, AC10, Y15, AF22, AF26, AF4, AD8, AG26, AH6, AD24, AF9, AA8, AC22, AE8, AF13, AB14, AF23, AG12, AB18, Y19, AG3, AE16, AB7]
        d: [J14, D6, J17, G7, F18, C6, H17, C18, D18, G16, G22, F12, D11, E24, H21, G9, A4, G13, H14, B8, C8, F7, B11, B22, A18, G8, J12, D9, C9, E7, H10, J10]
    hsma:
      index_origin: {clk_in_p: 1, clk_out_p: 1, clk_in_n: 1, clk_out_n: 1}
      pins:
        clk_in0: AG14
        clk_in_p: [Y2, J2]
        clk_out0: Y7
        clk_out_p: [G6, D2]
        d: [AB6, AF2, AE3, AC5]
        rx_led: AE1
        scl: AC3
        sda: AC1
        tx_led: AA3
        clk_in_n: [Y1, J1]
        clk_out_n: [G5, D1]
        rx_d_n: [AB1, Y3, U4, W1, V1, U1, U5, R1, N3, L3, L1, K1, J5, H3, G3, F1, F3]
        rx_d_p: [AB2, Y4, U3, W2, V2, U2, U6, R2, N4, L4, L2, K2, J6, H4, G4, F2, E3]
        tx_d_n: [R6, V3, T3, R4, M7, P1, M3, M1, L6, L8, K3, J3, K7, G1, F4, E1, C2]
        tx_d_p: [R7, V4, T4, R3, M8, P2, M4, M2, L7, K8, K4, J4, J7, G2, F5, E2, D3]
      overrides:
        "AG14": 1.8 V
        "D1": SSTL-2 CLASS II
        "D2": SSTL-2 CLASS II
        "G5": SSTL-2 CLASS II
        "G6": SSTL-2 CLASS II
    hsmb:
      index_origin: {clk_in_n: 1, clk_in_p: 1, clk_out_n: 1, clk_out_p: 1}
      pins:
        clk_in0: A15
        clk_out0: J22
        rx_led: F26
        scl: H25
        sda: H26
        tx_led: D28
        clk_in_n: [J28, Y28]
        clk_in_p: [J27, Y27]
        clk_out_n: [AD26, AD28]
        clk_out_p: [AC26, AD27]
        d: [G24, H23, G25, H24]
        rx_d_n: [F28, G28, K26, K28, L28, M28, P26, P28, R21, R23, T26, U28, V22, W27, V24, AB28, AC28]
        rx_d_p: [F27, G27, K25, K27, L27, M27, P25, P27, P21, R22, T25, U27, U22, W28, V23, AB27, AC27]
        tx_d_n: [J26, L24, M26, N26, R28, R26, U26, V28, V26, W26, Y26, AA26, AB26, Y24, AE28, Y22, W21]
        tx_d_p: [J25, L23, M25, N25, R27, R25, U25, V27, V25, W25, Y25, AA25, AB25, Y23, AE27, W22, V21]
      overrides:
        "A15": 1.8 V
    onboard_lcd_controller:
      pins:
        rstn: H7
        wen: AC4
        e_rdn: V7
        data: [AA4, AD1, V8, AB5, AE2, V5, V6, AB3]
        csn: AB24
        d_cn: D27
    onboard_lcd:
      pins:
        de: AC24
    onboard_leds:
      active: low
      iostandard: 1.8 V
      pins: [AD15, AE20, AF18, AD19, AE15, AC17, AG19, AF19]
    onboard_max_ctrl:
      iostandard: 1.8 V
      pins:
        csn: D23
        oen: E25
        wen: C15
        clk: D14
    cpu_resetn: { pins: T21, active: low }
    onboard_7seg:
      iostandard: 1.8 V
      index_origin: {anodes: 1}
      pins:
        ca: AD5
        cb: A3
        cc: C4
        cd: D4
        ce: E5
        cf: D5
        cg: AE6
        dp: AD4
        minus: G19
        anodes: [B3, C5, E4, C3]
    onboard_speaker: { pins: H22 }
    onboard_buttons:
      active: low
      iostandard: 1.8 V
      pins: [AD7, AC12, AH3, AA12]
    onboard_switches:
      iostandard: 1.8 V
      pins: [AC14, AD18, AG23, AC19, AD14, G20, AB15, AF25]
    onboard_usb:
      pins:
        ifclk: B15
        cmd_data: C27
        ren: G23
        wen: E26
        empty: F25
        full: F24
        fd: [L21, K22, L22, K21, J24, G26, J23, D26]
      overrides:
        "B15": 1.8 V
    onboard_fpga_jtag:   # FPGA JTAG (routed to HSMC ports)
      device: {"name": "FPGA JTAG (routed to HSMC ports)", "kind": "other"}
      iostandard: "2.5 V"
      pins: {"FPGA_JTAG_TCK": "P5", "FPGA_JTAG_TMS": "P8"}
