# alinx_axp391: ALINX AXP391 Development Board.

Board:
  id: alinx_axp391
  name: ALINX AXP391 Development Board
  url: https://www.pangomicro.com/open/4307.html
  status: active
  producer: alinx
  chip: PG2T390H-6IFFBG900
  bridges:
  - usb-jtag
  programmer: pango_pgm
  features:
  - ddr3_memory
  - ddr4_memory
  - ethernet_phy_gigabit
  - fmc_lpc
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - sfp_cage
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - micron_mt41k256m16
  - microchip_ksz9031rnx
  - silabs_cp2102
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
