# bittware_xup_vv8: BittWare XUP-VV8 Virtex UltraScale+ VU13P.

Board:
  id: bittware_xup_vv8
  name: BittWare XUP-VV8 Virtex UltraScale+ VU13P
  url: https://www.bittware-molex.com/products/xup-vv8/
  status: active
  producer: bittware
  chip: XCVU13P-2FHGB2104E
  bridges:
  - pcie-jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - pcie_endpoint
  - qsfp_cage
  - qspi_flash
  - usb_uart_bridge
  devices:
  - ftdi_ft4232h
  - silabs_si5342
  - silabs_si570
  - micron_n25q256a
  - ddr4_sodimm_socket
