# xilinx_alveo_u250 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/xilinx_alveo_u250.py


Board:
  id: xilinx_alveo_u250
  name: Alveo U250
  url: https://www.xilinx.com/products/boards-and-kits/alveo/u250.html
  producer: xilinx_amd
  chip: XCU250-FIGD2104-2L-E
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - pcie_edge_connector
  devices:
  - ddr4_sodimm_socket
  banks:
    cpu_resetn:
      pins: AL20
    onboard_switches:
      pins: [AN22, AM19, AL19, AP20]
    onboard_leds:
      pins: [BC21, BB21, BA20]
    onboard_uart:
      pins:
        rx: BF18
        tx: BB20
    i2c_scl:
      pins:
        pin: BF20
    i2c_sda:
      pins:
        pin: BF17
    pcie_clk_n:
      pins:
        pin: AM10
    pcie_clk_p:
      pins:
        pin: AM11
    pcie_rst_n:
      pins:
        pin: BD21
    pcie_rx_n:
      pins: [AF1, AG3, AH1, AJ3]
    pcie_rx_p:
      pins: [AF2, AG4, AH2, AJ4]
    pcie_tx_n:
      pins: [AF6, AG8, AH6, AJ8]
    pcie_tx_p:
      pins: [AF7, AG9, AH7, AJ9]
    qsfp_clk_n:
      pins:
        pin: P10
    qsfp_clk_p:
      pins:
        pin: P11
    qsfp_fs0:
      pins:
        pin: AR22
    qsfp_fs1:
      pins:
        pin: AU20
    qsfp_intl:
      pins:
        pin: AV21
    qsfp_lpmode:
      pins:
        pin: AV22
    qsfp_modprsl:
      pins:
        pin: BC19
    qsfp_modskll:
      pins:
        pin: AY20
    qsfp_refclk_reset:
      pins:
        pin: AR21
    qsfp_resetl:
      pins:
        pin: BC18
    qsfp_rxn:
      pins: [U3, T1, R3, P1]
    qsfp_rxp:
      pins: [U4, T2, R4, P2]
    qsfp_txn:
      pins: [U8, T6, R8, P6]
    qsfp_txp:
      pins: [U9, T7, R9, P7]
