# ice40hx8k_evb pin map.

Board:
  id: ice40hx8k_evb
  fpga:
    producer: Lattice
    family: ICE40
    part: iCE40HX8K-CT256

  # yosys synth flags.
  toolchain_options:
    yosys:
      synth_options: [dsp, noabc9]
      loader_board: "ice40_generic"
      device_part: "hx8k"
      device_pack: "ct256"
  pinBanks:
    clk: { pins: J3, frequency_mhz: 100 }
    onboard_buttons:
      pins: [K11, P13, R15]
    onboard_leds:
      pins: [M12, R16]
    onboard_switches:
      pins: [R1, N4]
    gpio:
      pins: [E4, B2, F5, B1, C1, C2, F4, D2, G5, D1, G4, E3]
    onboard_uart:
      pins:
        rx: H1
        tx: J2
    onboard_vga:
      pins:
        hs: G1
        vs: J5
        r: [H2, J4, G2, H4]
        g: [F1, H6, F2, H3]
        b: [F3, G3, E2, H5]
