"""
Vivado toolchain driver.

Given a resolved configuration + a user design_top, drive Vivado in batch mode
through synthesis -> place-and-route -> bitstream generation. Artifacts:

    <output>/top.sv             — codegen-produced top module
    <output>/constraints.xdc    — codegen-produced pin constraints
    <output>/build.tcl          — Vivado batch script
    <output>/vivado.log         — Vivado log
    <output>/top.bit            — final bitstream

The driver also supports a dry-run mode (set $UNIFPGA_DRY_RUN=1 in the
environment) which generates every artifact but does not execute Vivado.
"""

import logging
import os
import shutil
import subprocess

from tools import codegen
from tools import source_set


log = logging.getLogger(__name__)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))


def _resolve_vivado_bin(toolchain):
    install_dir = os.path.expanduser(toolchain.get("InstallDir") or "").rstrip("/")
    if install_dir:
        candidate = os.path.join(install_dir, "bin", "vivado")
        if os.path.exists(candidate):
            return candidate
    return shutil.which("vivado")


def _collect_sv_sources(repo, peripherals, user_design_top, generated_top):
    """Vivado reads .svh headers; unisim provides BUFG (no compat stubs); helpers/common ungated."""
    return source_set.collect_sources(
        repo, peripherals, user_design_top, generated_top,
        include_svh=True, gate_helpers=False, gate_common=False, compat_stubs=False)


def _emit_tcl(part_name, sv_files, xdc_path, output_dir, top_module="top",
              do_synth=True, do_pnr=True, do_bitstream=True):
    lines = []
    lines.append("# Vivado batch script — auto-generated by uni-fpga.")
    prj_dir = os.path.join(output_dir, "vivado_prj")
    lines.append("create_project unifpga_top {} -part {} -force".format(prj_dir, part_name))
    lines.append("")
    lines.append("# Source files")
    for sv in sv_files:
        lines.append("read_verilog -sv {{ {} }}".format(sv))
    lines.append("read_xdc {{ {} }}".format(xdc_path))
    lines.append("")
    if do_synth:
        # `elaborate` step performs RTL elaboration only — quick check that the
        # SystemVerilog parses and unifies. Full P&R steps are skipped.
        if not do_pnr:
            lines.append("synth_design -rtl -top {}".format(top_module))
        else:
            lines.append("synth_design -top {}".format(top_module))
            lines.append("write_checkpoint -force {}".format(os.path.join(output_dir, "post_synth.dcp")))
            lines.append("report_utilization -file {}".format(os.path.join(output_dir, "post_synth_util.rpt")))
            lines.append("report_timing_summary -file {}".format(os.path.join(output_dir, "post_synth_timing.rpt")))
        lines.append("")
    if do_pnr:
        lines.append("opt_design")
        lines.append("place_design")
        lines.append("phys_opt_design")
        lines.append("route_design")
        lines.append("write_checkpoint -force {}".format(os.path.join(output_dir, "post_route.dcp")))
        lines.append("report_utilization -file {}".format(os.path.join(output_dir, "post_route_util.rpt")))
        lines.append("report_timing_summary -file {}".format(os.path.join(output_dir, "post_route_timing.rpt")))
        lines.append("report_drc -file {}".format(os.path.join(output_dir, "post_route_drc.rpt")))
        lines.append("")
    if do_bitstream:
        lines.append("write_bitstream -force {}".format(os.path.join(output_dir, top_module + ".bit")))
    return "\n".join(lines) + "\n"


def synthesize(*, dir, configuration, board, board_pinmap, toolchain, peripherals,
               top, generated_top=None, include=None, output, step="full", **_):
    """Synthesize a configuration through Vivado. Returns 0 on success."""
    resolved = {
        "configuration": configuration,
        "board":         board,
        "board_pinmap":  board_pinmap,
        "toolchain":     toolchain,
        "peripherals":   peripherals,
    }

    if generated_top is None:
        generated_top = os.path.join(output, "top.sv")
        with open(generated_top, "w") as f:
            f.write(codegen.emit_top_sv(resolved))

    xdc_path = os.path.join(output, "constraints.xdc")
    with open(xdc_path, "w") as f:
        f.write(codegen.emit_xdc(resolved))
    log.info("Wrote %s", xdc_path)

    sv_files = _collect_sv_sources(REPO, peripherals, top, generated_top)

    # Boards may list a single Part: or a Parts: list (Arty A7's 35t/100t
    # variants etc.). Pick the configuration's nominated variant if specified;
    # otherwise default to the first.
    part_name = board.get("Part") or ""
    if not part_name and isinstance(board.get("Parts"), list):
        wanted = (configuration.get("part") or "").lower()
        chosen = None
        for entry in board["Parts"]:
            if wanted and entry.get("Name", "").lower() == wanted:
                chosen = entry
                break
        if chosen is None:
            chosen = board["Parts"][0]
            log.info("Board %s has multiple Parts; defaulting to %s",
                     board["Id"], chosen.get("Name") or chosen.get("Part"))
        part_name = chosen.get("Part") or ""
    if not part_name:
        log.error("Board %s has no 'Part' field — cannot drive Vivado.", board["Id"])
        return 1

    do_synth     = step in ("elaborate", "pnr", "full")
    do_pnr       = step in ("pnr", "full")
    do_bitstream = step == "full"

    tcl_path = os.path.join(output, "build.tcl")
    with open(tcl_path, "w") as f:
        f.write(_emit_tcl(part_name, sv_files, xdc_path, output,
                          do_synth=do_synth, do_pnr=do_pnr, do_bitstream=do_bitstream))
    log.info("Wrote %s", tcl_path)
    log.info("Source files (%d):", len(sv_files))
    for sv in sv_files:
        log.info("  - %s", os.path.relpath(sv, REPO) if sv.startswith(REPO) else sv)

    if os.environ.get("UNIFPGA_DRY_RUN"):
        log.info("[dry run] Vivado not invoked. Artifacts in %s", output)
        return 0

    vivado_bin = _resolve_vivado_bin(toolchain)
    if vivado_bin is None:
        log.error("Could not locate the `vivado` binary. Set toolchain.InstallDir "
                  "in config/toolchains.yml, put vivado on $PATH, or set "
                  "UNIFPGA_DRY_RUN=1 to skip the actual run.")
        return 1

    log_path = os.path.join(output, "vivado.log")
    journal_path = os.path.join(output, "vivado.jou")
    cmd = [vivado_bin, "-mode", "batch", "-source", tcl_path,
           "-log", log_path, "-journal", journal_path]
    log.info("Invoking Vivado: %s", " ".join(cmd))

    try:
        rc = subprocess.run(cmd, cwd=output).returncode
    except FileNotFoundError as exc:
        log.error("Vivado invocation failed: %s", exc)
        return 1

    if rc != 0:
        log.error("Vivado exited with code %d (see %s)", rc, log_path)
        return rc

    bit = os.path.join(output, "top.bit")
    if os.path.exists(bit):
        log.info("Bitstream ready: %s", bit)
    return 0


def _emit_program_tcl(bitstream_path, hw_device):
    """Vivado batch script that opens the hardware manager, locates the
    target FPGA, and downloads the bitstream over JTAG."""
    return (
        "open_hw_manager\n"
        "connect_hw_server -allow_non_jtag\n"
        "open_hw_target\n"
        "set_property PROGRAM.FILE {{ {bit} }} [get_hw_devices {dev}]\n"
        "current_hw_device [get_hw_devices {dev}]\n"
        "refresh_hw_device [current_hw_device]\n"
        "program_hw_devices [get_hw_devices {dev}]\n"
        "close_hw_target\n"
        "close_hw_manager\n"
    ).format(bit=bitstream_path, dev=hw_device)


def program(*, board, board_pinmap=None, toolchain, output, **_):
    """Download the previously-built bitstream to the connected board over JTAG.
    Runs `vivado -mode batch -source program.tcl`."""
    bit = os.path.join(output, "top.bit")
    if not os.path.exists(bit) and not os.environ.get("UNIFPGA_DRY_RUN"):
        log.error("Bitstream not found: %s — run synthesis first", bit)
        return 1

    # The hw_device pattern is typically `<chip-family>_0` for the first
    # device in the JTAG chain. e.g. xc7a100t_0 for Nexys 4 DDR.
    part = board.get("Part") or ""
    if not part and isinstance(board.get("Parts"), list):
        part = board["Parts"][0].get("Part") or ""
    # Strip the package + speed suffix to get the chip family.
    # xc7a100tcsg324-1 -> xc7a100t
    import re as _re
    m = _re.match(r"^(xc[0-9a-z]+?[0-9]+t)", part.lower())
    hw_device = (m.group(1) + "_0") if m else "*"

    tcl_path = os.path.join(output, "program.tcl")
    with open(tcl_path, "w") as f:
        f.write(_emit_program_tcl(bit, hw_device))
    log.info("Wrote %s", tcl_path)

    if os.environ.get("UNIFPGA_DRY_RUN"):
        log.info("[dry run] Vivado not invoked. Programming script: %s", tcl_path)
        return 0

    vivado_bin = _resolve_vivado_bin(toolchain)
    if vivado_bin is None:
        log.error("Could not locate the `vivado` binary for programming.")
        return 1

    cmd = [vivado_bin, "-mode", "batch", "-source", tcl_path,
           "-log", os.path.join(output, "program.log"),
           "-journal", os.path.join(output, "program.jou")]
    log.info("Programming via: %s", " ".join(cmd))
    rc = subprocess.run(cmd, cwd=output).returncode
    if rc != 0:
        log.error("Programming failed (exit %d). Is the board connected?", rc)
    return rc
