# alinx_axp110: ALINX AXP110 Development Board.

Board:
  id: alinx_axp110
  name: ALINX AXP110 Development Board
  url: https://www.pangomicro.com/open/4296.html
  status: active
  notes: PCIe 2.0 x4 + FMC LPC.
  producer: alinx
  chip: PG2L100H-6IFBG676
  bridges:
  - jtag
  programmer: pango_pgm
  features:
  - ddr3_memory
  - ethernet_phy_gigabit
  - fmc_lpc
  - gpio_header_generic
  - hdmi_output
  - jtag_header
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - microchip_ksz9031rnx
  - silabs_cp2102
  - micron_mt41j256m16
  - silicon_image_sil9134
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
