# Microchip (Actel) / PolarFire SoC
# PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.

Producer: Microchip (Actel)
Family: PolarFire SoC
Description: PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.
Boards:
  - Id: microchip_beaglev_fire
    BoardName: BeagleV-Fire
    Aliases: [beagleboard_beaglev_fire]
    Devices:
      - microchip_ksz9031rnx
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - winbond_w25q128
    BoardProducer: microchip
    Chip: MPFS025T-1FCVG484E
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    Features:
      - emmc_flash
      - ethernet_phy_gigabit
      - microsd_socket
      - qspi_flash
      - spi_flash
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://www.microchip.com/en-us/development-tool/beaglev-fire
    Status: active
  - Id: microchip_iglooicicle
    BoardName: PolarFire SoC Icicle Kit
    Features:
      - ethernet_phy_gigabit
      - microsd_socket
      - spi_flash
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Devices:
      - ftdi_ft4232h
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - winbond_w25q128
      - microchip_ksz9031rnx
    BoardProducer: microchip
    Chip: MPFS250T-FCVG484EES
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    BoardURL: https://www.microchip.com/en-us/development-tool/MPFS-ICICLE-KIT-ES
  - Id: microchip_polarfiresoc_disco
    BoardName: PolarFire SoC Discovery Kit
    Aliases: [microchip_iglooicicle_disco]
    Devices:
      - ftdi_ft4232h
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - winbond_w25q128
    BoardProducer: microchip
    Chip: MPFS095T-1FCSG325E
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    Features:
      - ethernet_phy_gigabit
      - microsd_socket
      - mikrobus_socket
      - mipi_csi2_input
      - qspi_flash
      - raspi_hat_header
      - spi_flash
      - usb_jtag_bridge
      - usb_powered
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://www.microchip.com/en-us/development-tool/mpfs-disco-kit
    Status: active
  - Id: microchip_polarfiresoc_video
    BoardName: PolarFire SoC Video Kit
    Features:
      - ethernet_phy_gigabit
      - microsd_socket
      - spi_flash
      - usb_uart_bridge
      - user_buttons
      - user_leds
    Devices:
      - ftdi_ft4232h
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - winbond_w25q128
      - microchip_ksz9031rnx
    BoardProducer: microchip
    Chip: MPFS250T-FCG1152EES
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    BoardURL: https://www.microchip.com/en-us/development-tool/MPFS-VIDEO-KIT
  - Id: microchip_pfsoc_disco_kit_v2
    BoardName: "PolarFire SoC Discovery Kit (MPFS095T-1FCSG325E rev2)"
    BoardProducer: microchip
    Chip: MPFS095T-1FCSG325E
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    Features:
      - ddr4_memory
      - ethernet_phy_gigabit
      - microsd_socket
      - spi_flash
      - usb_uart_bridge
      - user_leds
    Devices:
      - ftdi_ft4232h
      - microsd_socket_generic
      - winbond_w25q128
      - microchip_ksz9031rnx
    BoardURL: "https://www.microchip.com/en-us/development-tool/MPFS-DISCO-KIT"
    Status: active
