# cmod_a7 pin map.
#
# Source: Digilent Cmod-A7-Master.xdc (github.com/Digilent/digilent-xdc, MIT-licensed)
# Imported via tools/verify_pinmap_against_vendor.py.


Board:
  id: cmod_a7
  name: CMOD A7
  url: https://digilent.com/reference/programmable-logic/cmod-a7/start
  producer: digilent
  chips:
  - id: XC7A15T-CPG236I
    name: 15t
  - id: XC7A35T-CPG236I
    name: 35t
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - qspi_flash
  - rgb_leds
  - sram
  - usb_jtag_bridge
  - user_buttons
  - user_leds
  devices:
  - ftdi_ft2232h
  - pushbutton_smd_generic
  - led_discrete_generic
  - rgb_led_common_anode
  - micron_n25q032a
  - issi_is61wv5128bll
  documents:
  - id: xdc
    title: Digilent Cmod-A7-Master.xdc (github.com/Digilent/digilent-xdc, MIT)
    kind: constraints
    url: https://raw.githubusercontent.com/Digilent/digilent-xdc/00a3404901f35aa9567b01ecb3f2c233b6efe9f4/Cmod-A7-Master.xdc
    sha256: 56568df3868ef359e938ef8defab33e1814fe4153435e99e13da9260d9db4eaf
    bytes: 12909
    retrieved: '2026-09-25'
  defaults:
    iostandard: LVCMOS33

  banks:
    clk:
      pins: L17
    onboard_buttons:
      pins: [A18, B18]
    onboard_leds:
      pins: [A17, C16]
    onboard_rgb_led_0:
      pins:
        b: "B17"
        g: "B16"
        r: "C17"
    onboard_uart:
      pins:
        rx: "J17"
        tx: "J18"
    pmod_ja:
      pins: [G17, G19, N18, L18, H17, H19, J19, K18]
