# numato_mimas_a7: Mimas A7.

Board:
  id: numato_mimas_a7
  name: Mimas A7
  url: https://numato.com/product/mimas-a7-artix-7-fpga-development-board/
  producer: numato_lab
  chip: XC7A50T-1FGG484C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - dip_switches
  - microsd_socket
  - qspi_flash
  - usb_jtag_bridge
  - user_buttons
  - user_leds
  devices:
  - ftdi_ft2232h
  - micron_mt41k128m16
  - micron_n25q128a
  - led_discrete_generic
  - pushbutton_smd_generic
  - dip_switch_generic
  - microsd_socket_generic
