# trenz_te0725 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/trenz_te0725.py


Board:
  id: trenz_te0725
  name: TE0725
  url: https://shop.trenz-electronic.de/en/TE0725-04-72C-1-A-FPGA-Module-with-AMD-Artix-7A100T-2C-2-x-50-Pin-Header-3-5-x-7-3-cm
  producer: trenz_electronic
  chip: XC7A100T-2FGG484I
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - qspi_flash
  devices:
  - micron_mt41k128m16
  - micron_n25q128a
  banks:
    sys_clk:
      pins: P17
    cpu_resetn:
      pins: T8
    onboard_leds:
      pins: M16
    onboard_uart:
      pins:
        tx: L18
        rx: M18
    qspi_flash_clk:
      pins:
        pin: E9
    qspi_flash_cs_n:
      pins:
        pin: L13
    qspi_flash_dq:
      pins: [K17, K18, L14, M14]
    qspi_flash_hold:
      pins:
        pin: M14
    qspi_flash_miso:
      pins:
        pin: K18
    qspi_flash_mosi:
      pins:
        pin: K17
    qspi_flash_wp:
      pins:
        pin: L14
