# usb104_a7_100t pin map.
#
# Source: Digilent USB104-A7-100T-Master.xdc (github.com/Digilent/digilent-xdc, MIT-licensed)
# Imported via tools/verify_pinmap_against_vendor.py.


Board:
  id: usb104_a7_100t
  name: USB104 A7-100T
  producer: digilent
  chip: XC7A100T-1FTG256C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - microsd_socket
  - qspi_flash
  - usb_jtag_bridge
  - user_buttons
  - user_leds
  devices:
  - cypress_s25fl128s
  - micron_mt41k256m16
  - ftdi_ft2232h
  - microsd_socket_generic
  - pushbutton_smd_generic
  - led_discrete_generic
  defaults:
    iostandard: LVCMOS33

  banks:
    onboard_buttons:
      pins: ["V16", "U17"]
    onboard_leds:
      pins: ["R17", "P15", "R15", "T14"]
    pmod_ja:
      pins: ["F4", "F3", "E2", "D2", "H2", "G2", "C2", "C1"]
    pmod_jb:
      pins: ["C4", "B2", "B3", "B4", "B1", "A1", "A3", "A4"]
    pmod_jc:
      pins: ["C5", "C6", "B6", "C7", "A5", "A6", "B7", "D8"]
