# xilinx_ac701 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/xilinx_ac701.py


Board:
  id: xilinx_ac701
  name: AC701
  url: https://www.xilinx.com/products/boards-and-kits/ek-a7-ac701-g.html
  producer: xilinx_amd
  chip: XC7A200T-2FBG676C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - dip_switches
  - ethernet_phy_gigabit
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - usb_jtag_bridge
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - micron_mt41k256m16
  - micron_n25q256a
  - marvell_88e1116r
  - silabs_cp2103
  - ftdi_ft2232h
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
  - dip_switch_generic
  banks:
    cpu_resetn:
      pins: U4
    onboard_leds:
      pins: [M26, T24, T25, R26]
    onboard_uart:
      pins:
        cts: V19
        rts: W19
        tx: U19
        rx: T19
    ethernet_rx:
      pins:
        pin: U21
    ethernet_tx:
      pins:
        pin: U22
    ethernet_mdio:
      pins:
        pin: T14
    ethernet_mdc:
      pins:
        pin: W18
    ethernet_rst_n:
      pins:
        pin: V18
    ethernet_rx_ctl:
      pins:
        pin: U14
    ethernet_rx_data:
      pins: [U17, V17, V16, V14]
    ethernet_tx_ctl:
      pins:
        pin: T15
    ethernet_tx_data:
      pins: [U16, U15, T18, T17]
    pcie_clk_n:
      pins:
        pin: E11
    pcie_clk_p:
      pins:
        pin: F11
    pcie_rst_n:
      pins:
        pin: M20
    pcie_rx_n:
      pins: [C12, A13, C14, A11]
    pcie_rx_p:
      pins: [D12, B13, D14, B11]
    pcie_tx_n:
      pins: [C10, A9, C8, A7]
    pcie_tx_p:
      pins: [D10, B9, D8, B7]
    qspi_flash_cs_n:
      pins:
        pin: P18
    qspi_flash_dq:
      pins: [R14, R15, P14, N14]
    qspi_flash_hold:
      pins:
        pin: N14
    qspi_flash_miso:
      pins:
        pin: R15
    qspi_flash_mosi:
      pins:
        pin: R14
    qspi_flash_wp:
      pins:
        pin: P14
    sfp_rxn:
      pins:
        pin: AD12
    sfp_rxp:
      pins:
        pin: AC12
    sfp_txn:
      pins:
        pin: AD10
    sfp_txp:
      pins:
        pin: AC10
