# alinx_ax301 pin map.
# Sources (local Alinx docs):
#   ~/Alinx/.../AX301_CD_20210602.rar (streamed 47 constraint files; 261 signals)

Board:
  id: alinx_ax301
  pinBanks:
    sys_clk:
      frequency_mhz: 50
      pins: PIN_E1
    cpu_resetn:
      active: low
      pins: PIN_N13
    onboard_buttons:
      active: low
      pins: [PIN_M15, PIN_M15, PIN_M16, PIN_E16]
    onboard_leds:
      pins: [PIN_E10, PIN_F9, PIN_C9, PIN_D9]
    onboard_uart:
      pins:
        tx: PIN_N1
        rx: PIN_M2
    microsd:
      pins:
        dclk: PIN_D12
        miso: PIN_E15
        mosi: PIN_F10
        ncs: PIN_D11
