# Microchip (Actel) / PolarFire SoC — chip registry
# PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.

Family:
  id: polarfire_soc
  producer: microchip
  name: PolarFire SoC
  description: PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.
  default_toolchains:
    - libero_soc[*]
  chips:
    - id: MPFS025T-1FCVG484E
    - id: MPFS025T-FCSG325E
    - id: MPFS095T-1FCSG325E
    - id: MPFS250T-FCG1152EES
    - id: MPFS250T-FCVG484E
    - id: MPFS250T-FCVG484EES
