# lattice_certusnx_versa pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/lattice_certuspro_nx_versa.py


Board:
  id: lattice_certusnx_versa
  name: Certus-NX Versa Eval Board
  url: https://www.latticesemi.com/products/developmentboardsandkits/certus_nx_versa_eval
  producer: lattice
  chip: LFD2NX-40-8BG256C
  bridges:
  - jtag
  programmer: openFPGALoader
  features:
  - microsd_socket
  - pcie_endpoint
  - usb_jtag_bridge
  devices:
  - ftdi_ft2232h
  - microsd_socket_generic
  banks:
    onboard_buttons:
      pins: H21
    onboard_leds:
      pins: [R5, R4, R8, R9, U8, R7, R6, P8]
    onboard_uart:
      pins:
        rx: L8
        tx: M9
    i2c_scl:
      pins:
        pin: M7
    i2c_sda:
      pins:
        pin: M6
    pcie_clk_n:
      pins:
        pin: E20
    pcie_clk_p:
      pins:
        pin: F20
    pcie_perst:
      pins:
        pin: R26
    pcie_refret:
      pins: [E22, G21, E19, D18]
    pcie_rext:
      pins: [E21, G20, D19, C18]
    pcie_rx_n:
      pins: [G25, D25, B23, C22]
    pcie_rx_p:
      pins: [G24, E24, C24, C21]
    pcie_tx_n:
      pins: [E26, B26, A24, A21]
    pcie_tx_p:
      pins: [F26, C26, A25, A22]
    qspi_flash_clk:
      pins:
        pin: G6
    qspi_flash_cs_n:
      pins:
        pin: H3
    qspi_flash_dq:
      pins: [H7, H6, K5, H4]
    qspi_flash_hold:
      pins:
        pin: H4
    qspi_flash_miso:
      pins:
        pin: H6
    qspi_flash_mosi:
      pins:
        pin: H7
    qspi_flash_wp:
      pins:
        pin: K5
    sys_clk_n:
      pins:
        pin: AB18
    sys_clk_p:
      pins:
        pin: AB19
