# Gowin / AroraV/GW5AT — chip registry
# GW5A with hard RISC-V core.

Family:
  id: arorav_gw5at
  producer: gowin_semi
  name: AroraV/GW5AT
  description: GW5A with hard RISC-V core.
  default_toolchains:
    - gowin_standard[*]
  chips:
    - id: GW5AT-LV138PG484AC1/I0
    - id: GW5AT-LV60PG484AC1/I0
    - id: GW5AT-LV60UG225C1/I0
