# Gowin / AroraV/GW5AST — chip registry
# GW5A with safety/security features.

Family:
  id: arorav_gw5ast
  producer: gowin_semi
  name: AroraV/GW5AST
  description: GW5A with safety/security features.
  default_toolchains:
    - gowin_standard[*]
  chips:
    - id: GW5AST-LV138FPG676AES
    - id: GW5AST-LV138PG484AC1/I0
