# pangomicro_alinx_pgl22g: ALINX PGL22G Development Board.

Board:
  id: pangomicro_alinx_pgl22g
  name: ALINX PGL22G Development Board
  url: https://www.pangomicro.com/open/4261.html
  status: active
  notes: ALINX third-party SoM+baseboard kit; 256 MB DDR3, 128 Mbit QSPI.
  producer: pangomicro
  chip: PGL22G-6MBG324
  bridges:
  - jtag
  programmer: pango_pgm
  features:
  - ddr3_memory
  - ethernet_phy_gigabit
  - gpio_header_generic
  - hdmi_output
  - jtag_header
  - microsd_socket
  - parallel_camera_input
  - qspi_flash
  - usb_2_device
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - silabs_cp2102
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
