# alinx_axku062: Alinx AXKU062.

Board:
  id: alinx_axku062
  name: Alinx AXKU062
  url: https://www.en.alinx.com/Product/FPGA-Development-Boards/Kintex-UltraScale.html
  status: active
  producer: alinx
  chip: XCKU060-2FFVA1156I
  bridges:
  - usb-jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - fmc_hpc
  - fmc_lpc
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - silabs_cp2102
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
