# numato_aller pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/numato_aller.py


Board:
  id: numato_aller
  name: Aller
  status: eol
  producer: numato_lab
  chip: XCKU040-1FBVA676C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - pcie_edge_connector
  - qspi_flash
  - usb_jtag_bridge
  - user_buttons
  - user_leds
  devices:
  - ftdi_ft2232h
  - micron_n25q128a
  - ddr3_sodimm_socket
  - led_discrete_generic
  - pushbutton_smd_generic
  banks:
    sys_clk:
      pins: W19
    onboard_leds:
      pins: [AB21, AB22, U20]
    pcie_clk_n:
      pins:
        pin: E6
    pcie_clk_p:
      pins:
        pin: F6
    pcie_rst_n:
      pins:
        pin: AB20
    pcie_rx_n:
      pins: [A8, C11, A10, C9]
    pcie_rx_p:
      pins: [B8, D11, B10, D9]
    pcie_tx_n:
      pins: [A4, C5, A6, C7]
    pcie_tx_p:
      pins: [B4, D5, B6, D7]
    rgb_led_b:
      pins:
        pin: U20
    rgb_led_g:
      pins:
        pin: AB22
    rgb_led_r:
      pins:
        pin: AB21
