# xilinx_kcu105 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/xilinx_kcu105.py


Board:
  id: xilinx_kcu105
  name: KCU105
  url: https://www.xilinx.com/products/boards-and-kits/kcu105.html
  producer: xilinx_amd
  chip: XCKU040-2FFVA1156E
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - dip_switches
  - ethernet_phy_gigabit
  - microsd_socket
  - pcie_endpoint
  - qspi_flash
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - micron_mt40a256m16
  - micron_n25q256a
  - marvell_88e1111
  - silabs_cp2105
  - ftdi_ft4232h
  - microsd_socket_generic
  - led_discrete_generic
  - pushbutton_smd_generic
  - dip_switch_generic
  - ddr4_sodimm_socket
  - silabs_si570
  banks:
    cpu_resetn:
      pins: AN8
    onboard_leds:
      pins: [AP8, H23, P20, P21, N22, M22, R23, P23]
    onboard_uart:
      pins:
        cts: L23
        rts: K27
        tx: K26
        rx: G25
    hdmi_clk:
      pins:
        pin: AF13
    hdmi_d:
      pins: [AK11, AP11, AP13, AN13, AN11, AM11, AN12, AL12, AK12, AL13, AK13, AD11, AH12, AG12, AG10, AK8]
    hdmi_de:
      pins:
        pin: AE11
    hdmi_hsync:
      pins:
        pin: AE13
    hdmi_spdif:
      pins:
        pin: AE12
    hdmi_spdif_out:
      pins:
        pin: AF12
    hdmi_vsync:
      pins:
        pin: AH13
    i2c_scl:
      pins:
        pin: J24
    i2c_sda:
      pins:
        pin: J25
    microsd_clk:
      pins:
        pin: AL10
    microsd_cmd:
      pins:
        pin: AD9
    microsd_data:
      pins: [AP9, AN9, AH9, AH8]
    pcie_clk_n:
      pins:
        pin: AB5
    pcie_clk_p:
      pins:
        pin: AB6
    pcie_rst_n:
      pins:
        pin: K22
    pcie_rx_n:
      pins: [AB1, AD1, AF1, AH1, AJ3, AK1, AM1, AP1]
    pcie_rx_p:
      pins: [AB2, AD2, AF2, AH2, AJ4, AK2, AM2, AP2]
    pcie_tx_n:
      pins: [AC3, AE3, AG3, AH5, AK5, AL3, AM5, AN3]
    pcie_tx_p:
      pins: [AC4, AE4, AG4, AH6, AK6, AL4, AM6, AN4]
    qspi_flash_cs_n:
      pins:
        pin: G26
    qspi_flash_dq:
      pins: [M20, L20, R21, R22]
    sfp_rxn:
      pins:
        pin: V1
    sfp_rxp:
      pins:
        pin: V2
    sfp_txn:
      pins:
        pin: W3
    sfp_txp:
      pins:
        pin: W4
