# adiuvo_astria_embedded_tile: Astria Embedded System Tile.

Board:
  id: adiuvo_astria_embedded_tile
  name: Astria Embedded System Tile
  url: https://www.adiuvoengineering.com/product-page/astria-embedded-system-tile
  status: active
  producer: adiuvo
  chip: XC7S25-1CSGA225C
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - jtag_header
  - qspi_flash
  - user_buttons
  - user_leds
  devices:
  - led_discrete_generic
  - pushbutton_smd_generic
