# papilio_one: Papilio One.

Board:
  id: papilio_one
  name: Papilio One
  url: https://papilio.cc/index.php?n=Papilio.PapilioOne
  producer: papilio
  chip: XC3S500E-VQ100
  bridges:
  - papilio-ft2232
  programmer: papilio_loader
  extra_programmers:
  - papilio_loader[*]
