# karnix_ecp5 pin map.

Board:
  id: karnix_ecp5
  fpga:
    producer: Lattice
    family: ECP5
    part: LFE5UM-25F
  defaults:
    iostandard: LVCMOS33

  # yosys synth flags.
  toolchain_options:
    yosys:
      synth_options: [noabc9]
      loader_ftdi_channel: "0"
      device_part: "25k"
      device_pack: "CABGA256"
      speed: "6"
  pinBanks:
    clk: { pins: B9, frequency_mhz: 25 }
    onboard_leds:
      pins: [A13, A14, A15, B14]
    onboard_buttons:
      pins: [B13, C13, D13, E13]
    gpio:
      pins: [L1, L2, M1, M2, K4, K5, L4, L5, N1, P2, L3, M3, P1, R1]
    onboard_vga:
      pins:
        r: [M4, N3, N4, D16]
        g: [R2, T2, P4, R3]
        b: [R4, T3, R5, T4]
        hs: M5
        vs: N5
    onboard_switches:
      pins: [A7, A8]
    onboard_uart:
      pins:
        rx: D12
        tx: E12
