# Gowin / LittleBee/GW1NS — chip registry
# GW1N with Cortex-M3 hard core.

Family:
  id: littlebee_gw1ns
  producer: gowin_semi
  name: LittleBee/GW1NS
  description: GW1N with Cortex-M3 hard core.
  default_toolchains:
    - gowin_eda[*]
    - nextpnr_apicula[*]
  chips:
    - id: GW1NS-LV4CQN48C7/I6
