# Gowin / LittleBee/GW1NSR — chip registry
# GW1NS with embedded SDRAM.

Family:
  id: littlebee_gw1nsr
  producer: gowin_semi
  name: LittleBee/GW1NSR
  description: GW1NS with embedded SDRAM.
  default_toolchains:
    - gowin_eda[*]
    - nextpnr_apicula[*]
  chips:
    - id: GW1NSR-LV4CQN48GC7/I6
    - id: GW1NSR-LV4CQN48PC6/I5
    - id: GW1NSR-LV4CQN48PC7/I6
