# Altera (Intel) / Agilex 5 — chip registry
# Mid-range Agilex. Quartus Prime Pro.

Family:
  id: agilex_5
  producer: intel_altera
  name: Agilex 5
  description: Mid-range Agilex. Quartus Prime Pro.
  default_toolchains:
    - quartus_prime_pro[*]
  chips:
    - id: A5D029BB32AE6SR0
    - id: A5ED014BB32AE6SR0
    - id: A5ED065BB32AE6SR0
    - id: A5EB013BB23BE4SCS
    - id: A5ED013BB32AE4SCS
    - id: A5ED065BB32AE4S
