# Altera (Intel) / Cyclone IV — chip registry
# 60 nm Cyclone (2009). Quartus Prime Lite.

Family:
  id: cyclone_iv
  producer: intel_altera
  name: Cyclone IV
  description: 60 nm Cyclone (2009). Quartus Prime Lite.
  default_toolchains:
    - quartus_prime_lite[*]
  chips:
    - id: EP4CE10E22C8N
    - id: EP4CE10F17C8
    - id: EP4CE115F29C7
    - id: EP4CE115F29C7N
    - id: EP4CE15F23C8
    - id: EP4CE15F23C8N
    - id: EP4CE22F17C6N
    - id: EP4CE55F23C8N
    - id: EP4CE6E22C8
    - id: EP4CE6F17C8
    - id: EP4CE75F23C8N
    - id: EP4CGX150DF27C7N
    - id: EP4CGX150DF31C7N
    - id: EP4CGX22CF19C6N
    - id: EP4CGX150DF27I7N
    - id: EP4CE30F23C8
