# Xilinx (AMD) / Artix Ultrascale+ — chip registry

Family:
  id: artix_ultrascale_plus
  producer: xilinx_amd
  name: Artix Ultrascale+
  description: 16 nm cost-optimized Artix UltraScale+. Vivado.
  default_toolchains:
    - vivado[*]
  chips:
    - id: XCAU15P-2FFVB676E
    - id: XCAU25P-2E
    - id: XCAU15P-2FFVB676I
    - id: XCAU25P-2FFVB676I
