# Xilinx (AMD) / Kintex Ultrascale+ — chip registry
# 16 nm Kintex follow-on. Vivado.

Family:
  id: kintex_ultrascale_plus
  producer: xilinx_amd
  name: Kintex Ultrascale+
  description: 16 nm Kintex follow-on. Vivado.
  default_toolchains:
    - vivado[*]
  chips:
    - id: XCKU11P-2FFVE1517E
    - id: XCKU15P-2FFVE1760E
    - id: XCKU5P-2FFVB676E
    - id: XCKU3P-2FFVB676I
    - id: XCKU15P-2FFVE1517I-CIV
    - id: XCKU15P-2FFVE1517I
    - id: XCKU5P-2FFVB676I
