# Xilinx (AMD) / Virtex Ultrascale+ — chip registry
# 16 nm. Vivado.

Family:
  id: virtex_ultrascale_plus
  producer: xilinx_amd
  name: Virtex Ultrascale+
  description: 16 nm. Vivado.
  default_toolchains:
    - vivado[*]
  chips:
    - id: XCU200-2FSGD2104E
    - id: XCU250-FIGD2104-2L-E
    - id: XCU26-L2FSVH2892E
    - id: XCU280-L2FSVH2892E
    - id: XCU50-FSVH2104-2-E
    - id: XCU55C-FSVH2892E
    - id: XCVU13P-2FHGB2104E
    - id: XCVU19P-2FSVB3824E
    - id: XCVU29P-L2FSGA2577E
    - id: XCVU37P-L2FSVH2892E
    - id: XCVU9P-2FLGA2104E
    - id: XCVU9P-L2FLGA2104E
    - id: XCVU9P-L2FSGD2104E
    - id: XCVU37P-2FSVH2892E
    - id: XCVU7P-2FLVB2104E
    - id: XCVU13P-2FHGB2104I
    - id: XCVU9P-2FLGB2104E
