# Xilinx (AMD) / Zynq Ultrascale+ — chip registry
# 16 nm A53 quad + R5 + UltraScale+ PL MPSoC. Vivado.

Family:
  id: zynq_ultrascale_plus
  producer: xilinx_amd
  name: Zynq Ultrascale+
  description: 16 nm A53 quad + R5 + UltraScale+ PL MPSoC. Vivado.
  default_toolchains:
    - vivado[*]
  chips:
    - id: XCK24-SFVC784
    - id: XCK26-SFVC784
    - id: XCU25
    - id: XCZU11EG-2FFVC1156E
    - id: XCZU11EG-2FFVC1156I
    - id: XCZU11EG-2FFVF1517I
    - id: XCZU15EG-1FFVC900I
    - id: XCZU15EG-2FFVB1156I
    - id: XCZU17EG-2FFVC1760I
    - id: XCZU17EG-2FFVD1760E
    - id: XCZU19EG-2FFVB1517I
    - id: XCZU19EG-2FFVC1760I
    - id: XCZU19EG-2FFVD1760E
    - id: XCZU19EG-2FFVD1760I
    - id: XCZU1CG-1SBVA484
    - id: XCZU2CG-1SFVC784E
    - id: XCZU2EG-1SFVC784I
    - id: XCZU2EG-L1SFVC784I4524
    - id: XCZU3CG-L1SFVC784I
    - id: XCZU3EG
    - id: XCZU3EG-1SBVA484E
    - id: XCZU3EG-1SFVA625
    - id: XCZU3EG-1SFVA625I
    - id: XCZU3EG-1SFVC784E
    - id: XCZU3EG-1SFVC784I
    - id: XCZU3EG-2SBVA484I
    - id: XCZU3EG-2SFVC784E
    - id: XCZU3EG-SFVC784
    - id: XCZU4EV-1SFVC784E
    - id: XCZU4EV-1SFVC784I
    - id: XCZU4EV-2SFVC784I
    - id: XCZU5EG-1SFVC784
    - id: XCZU5EV-1SFVC784I
    - id: XCZU5EV-2SFVC784I
    - id: XCZU7CG-2FFVC1156E
    - id: XCZU7EV
    - id: XCZU7EV-1FBVB900I
    - id: XCZU7EV-1FFVC1156E
    - id: XCZU7EV-1FFVC1156I
    - id: XCZU7EV-1FFVF1517E
    - id: XCZU7EV-2FBVB900I
    - id: XCZU7EV-2FFVC1156E
    - id: XCZU7EV-FBVB900
    - id: XCZU9EG-1FFVC900I
    - id: XCZU9EG-2FFVB1156E
    - id: XCZU9EG-2FFVB1156I
    - id: XCZU9EG-2FFVC900I
    - id: xczu1cgsbva484-1
    - id: xczu3eg-1sfvc784e
    - id: xczu5ev-2sfvc784i
    - id: XCZU7EV-2FFVC1156I
    - id: XCK26-SFVC784-2LV-C
    - id: XCZU15EG-2FFVC900I
