# Altera (Intel) / Agilex 7 — chip registry
# Mainstream Agilex high-perf. Quartus Prime Pro.

Family:
  id: agilex_7
  producer: intel_altera
  name: Agilex 7
  description: Mainstream Agilex high-perf. Quartus Prime Pro.
  default_toolchains:
    - quartus_prime_pro[*]
  chips:
    - id: AGFB014R24A2E2V
    - id: AGFB014R24A2E2VR0
    - id: AGFB014R24B2E2V
    - id: AGFB023R25A2E2VR0
    - id: AGFB027R24C2E2VR2
    - id: AGFB027R25A2E2V
    - id: AGIB023R29B1E1V
    - id: AGIB027R29A1E2VR0
    - id: AGIB027R29A1E2VR3
    - id: AGIB041R29A1E2VR0
    - id: AGMF039R47A1E2VR0
    - id: AGMF039R47A2E1V
    - id: AGFD023R24C2E1VC
    - id: AGIB027R31B1E1VC
    - id: AGIB023R18A1E1V
    - id: AGMF039R47A1E2VC
