# Lattice / Certus-NX
# Industrial Nexus FPGA. Radiant + nextpnr-nexus.

Producer: Lattice
Family: Certus-NX
Description: Industrial Nexus FPGA. Radiant + nextpnr-nexus.
Boards:
  - Id: lattice_certusnx_versa
    BoardName: Certus-NX Versa Eval Board
    Features:
      - microsd_socket
      - pcie_endpoint
      - usb_jtag_bridge
    Devices:
      - ftdi_ft2232h
      - microsd_socket_generic
    BoardProducer: lattice
    Chip: LFD2NX-40-8BG256C
    Bridges:
      - jtag
    Programmer: openFPGALoader
    BoardURL: "https://www.latticesemi.com/products/developmentboardsandkits/certus_nx_versa_eval"
  - Id: lattice_crosslink_nx_evn
    BoardName: CrossLink-NX Evaluation Board
    Features:
      - microsd_socket
      - usb_jtag_bridge
    Devices:
      - ftdi_ft2232h
      - microsd_socket_generic
    BoardProducer: lattice
    Chip: LIFCL-40-9BG400C
    Bridges:
      - jtag
    Programmer: openFPGALoader
    BoardURL: "https://www.latticesemi.com/en/Products/DevelopmentBoardsAndKits/CrossLink-NXEvaluationBoard"
