# iwave_rainbow_g63m: iW-RainboW-G63M Versal Premium SoM.

Board:
  id: iwave_rainbow_g63m
  name: iW-RainboW-G63M Versal Premium SoM
  url: https://www.iwavesystems.com/product/versal-premium-system-on-module/
  status: active
  producer: iwave
  chip: XCVP1502-1MSEVSVA2197
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - ddr4_memory
  - emmc_flash
  - ethernet_phy_gigabit
  - lpddr4_memory
  - qspi_flash
  - usb_2_otg
  - usb_jtag_bridge
  - usb_uart_bridge
  devices:
  - ftdi_ft4232h
  - micron_mt40a256m16
  - macronix_mx25l25645g
