# xilinx_vek280: VEK280.

Board:
  id: xilinx_vek280
  name: VEK280
  url: https://www.xilinx.com/products/boards-and-kits/vek280.html
  producer: xilinx_amd
  chip: XCVE2802-2MSEVSVH1760
  bridges:
  - jtag
  programmer: vivado_hw
  features:
  - dip_switches
  - ethernet_phy_gigabit
  - microsd_socket
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - microsd_socket_generic
  - silabs_cp2108
  - ftdi_ft4232h
  - led_discrete_generic
  - pushbutton_smd_generic
  - dip_switch_generic
  - marvell_88e1512
