# qmtech_cyclone_ep4cgx150_core pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/qmtech_ep4cgx150.py


Board:
  id: qmtech_cyclone_ep4cgx150_core
  name: QMtech Cyclone IV GX EP4CGX150 Core Board
  url: https://qmtech.aliexpress.com/store/1199788
  status: active
  producer: qmtech
  chip: EP4CGX150DF27C7N
  bridges:
  - usb-jtag
  programmer: quartus_pgm
  features:
  - qspi_flash
  - sdr_sdram
  - user_buttons
  - user_leds
  devices:
  - winbond_w9825g6kh
  - led_discrete_generic
  - pushbutton_smd_generic
  banks:
    sys_clk:
      pins: B14
    qspi_flash_clk:
      pins:
        pin: F6
    qspi_flash_cs_n:
      pins:
        pin: D5
    qspi_flash_miso:
      pins:
        pin: D6
    qspi_flash_mosi:
      pins:
        pin: E6
