# Anlogic / Phoenix EF3 — chip registry
# Anlogic Phoenix. TD.

Family:
  id: phoenix_ef3
  producer: anlogic
  name: Phoenix EF3
  description: Anlogic Phoenix. TD.
  default_toolchains:
    - td[*]
  chips:
    - id: EF3L185BG256C
