# htg_700: HTG-700 Virtex-7 V2000T/X690T PCIe Dev Board.

Board:
  id: htg_700
  name: HTG-700 Virtex-7 V2000T/X690T PCIe Dev Board
  url: https://www.hitechglobal.com/boards/virtex7_v2000t.htm
  status: active
  producer: hitech_global
  chip: XC7VX690T-2FFG1761C
  bridges:
  - pcie-jtag
  - usb-jtag
  programmer: vivado_hw
  features:
  - ddr3_memory
  - dip_switches
  - ethernet_phy_gigabit
  - fmc_hpc
  - pcie_endpoint
  - qspi_flash
  - usb_jtag_bridge
  - usb_uart_bridge
  - user_buttons
  - user_leds
  devices:
  - ftdi_ft2232h
  - silabs_si570
  - micron_n25q256a
  - ddr3_sodimm_socket
  - marvell_88e1512
  - led_discrete_generic
  - pushbutton_smd_generic
  - dip_switch_generic
